// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: List.proto

package com.yoti.api.client.spi.remote.proto;

public final class AttributeListProto {
  private AttributeListProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface AttributeAndIdOrBuilder extends
      // @@protoc_insertion_point(interface_extends:attrpubapi_v1.AttributeAndId)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional .attrpubapi_v1.Attribute attribute = 1;</code>
     * @return Whether the attribute field is set.
     */
    boolean hasAttribute();
    /**
     * <code>optional .attrpubapi_v1.Attribute attribute = 1;</code>
     * @return The attribute.
     */
    com.yoti.api.client.spi.remote.proto.AttributeProto.Attribute getAttribute();
    /**
     * <code>optional .attrpubapi_v1.Attribute attribute = 1;</code>
     */
    com.yoti.api.client.spi.remote.proto.AttributeProto.AttributeOrBuilder getAttributeOrBuilder();

    /**
     * <code>optional bytes attribute_id = 2;</code>
     * @return Whether the attributeId field is set.
     */
    boolean hasAttributeId();
    /**
     * <code>optional bytes attribute_id = 2;</code>
     * @return The attributeId.
     */
    com.google.protobuf.ByteString getAttributeId();
  }
  /**
   * Protobuf type {@code attrpubapi_v1.AttributeAndId}
   */
  public static final class AttributeAndId extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:attrpubapi_v1.AttributeAndId)
      AttributeAndIdOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use AttributeAndId.newBuilder() to construct.
    private AttributeAndId(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private AttributeAndId() {
      attributeId_ = com.google.protobuf.ByteString.EMPTY;
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new AttributeAndId();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private AttributeAndId(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              com.yoti.api.client.spi.remote.proto.AttributeProto.Attribute.Builder subBuilder = null;
              if (((bitField0_ & 0x00000001) != 0)) {
                subBuilder = attribute_.toBuilder();
              }
              attribute_ = input.readMessage(com.yoti.api.client.spi.remote.proto.AttributeProto.Attribute.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(attribute_);
                attribute_ = subBuilder.buildPartial();
              }
              bitField0_ |= 0x00000001;
              break;
            }
            case 18: {
              bitField0_ |= 0x00000002;
              attributeId_ = input.readBytes();
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.yoti.api.client.spi.remote.proto.AttributeListProto.internal_static_attrpubapi_v1_AttributeAndId_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.yoti.api.client.spi.remote.proto.AttributeListProto.internal_static_attrpubapi_v1_AttributeAndId_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.yoti.api.client.spi.remote.proto.AttributeListProto.AttributeAndId.class, com.yoti.api.client.spi.remote.proto.AttributeListProto.AttributeAndId.Builder.class);
    }

    private int bitField0_;
    public static final int ATTRIBUTE_FIELD_NUMBER = 1;
    private com.yoti.api.client.spi.remote.proto.AttributeProto.Attribute attribute_;
    /**
     * <code>optional .attrpubapi_v1.Attribute attribute = 1;</code>
     * @return Whether the attribute field is set.
     */
    @java.lang.Override
    public boolean hasAttribute() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <code>optional .attrpubapi_v1.Attribute attribute = 1;</code>
     * @return The attribute.
     */
    @java.lang.Override
    public com.yoti.api.client.spi.remote.proto.AttributeProto.Attribute getAttribute() {
      return attribute_ == null ? com.yoti.api.client.spi.remote.proto.AttributeProto.Attribute.getDefaultInstance() : attribute_;
    }
    /**
     * <code>optional .attrpubapi_v1.Attribute attribute = 1;</code>
     */
    @java.lang.Override
    public com.yoti.api.client.spi.remote.proto.AttributeProto.AttributeOrBuilder getAttributeOrBuilder() {
      return attribute_ == null ? com.yoti.api.client.spi.remote.proto.AttributeProto.Attribute.getDefaultInstance() : attribute_;
    }

    public static final int ATTRIBUTE_ID_FIELD_NUMBER = 2;
    private com.google.protobuf.ByteString attributeId_;
    /**
     * <code>optional bytes attribute_id = 2;</code>
     * @return Whether the attributeId field is set.
     */
    @java.lang.Override
    public boolean hasAttributeId() {
      return ((bitField0_ & 0x00000002) != 0);
    }
    /**
     * <code>optional bytes attribute_id = 2;</code>
     * @return The attributeId.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString getAttributeId() {
      return attributeId_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) != 0)) {
        output.writeMessage(1, getAttribute());
      }
      if (((bitField0_ & 0x00000002) != 0)) {
        output.writeBytes(2, attributeId_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, getAttribute());
      }
      if (((bitField0_ & 0x00000002) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, attributeId_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.yoti.api.client.spi.remote.proto.AttributeListProto.AttributeAndId)) {
        return super.equals(obj);
      }
      com.yoti.api.client.spi.remote.proto.AttributeListProto.AttributeAndId other = (com.yoti.api.client.spi.remote.proto.AttributeListProto.AttributeAndId) obj;

      if (hasAttribute() != other.hasAttribute()) return false;
      if (hasAttribute()) {
        if (!getAttribute()
            .equals(other.getAttribute())) return false;
      }
      if (hasAttributeId() != other.hasAttributeId()) return false;
      if (hasAttributeId()) {
        if (!getAttributeId()
            .equals(other.getAttributeId())) return false;
      }
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasAttribute()) {
        hash = (37 * hash) + ATTRIBUTE_FIELD_NUMBER;
        hash = (53 * hash) + getAttribute().hashCode();
      }
      if (hasAttributeId()) {
        hash = (37 * hash) + ATTRIBUTE_ID_FIELD_NUMBER;
        hash = (53 * hash) + getAttributeId().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.yoti.api.client.spi.remote.proto.AttributeListProto.AttributeAndId parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.yoti.api.client.spi.remote.proto.AttributeListProto.AttributeAndId parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.yoti.api.client.spi.remote.proto.AttributeListProto.AttributeAndId parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.yoti.api.client.spi.remote.proto.AttributeListProto.AttributeAndId parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.yoti.api.client.spi.remote.proto.AttributeListProto.AttributeAndId parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.yoti.api.client.spi.remote.proto.AttributeListProto.AttributeAndId parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.yoti.api.client.spi.remote.proto.AttributeListProto.AttributeAndId parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.yoti.api.client.spi.remote.proto.AttributeListProto.AttributeAndId parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.yoti.api.client.spi.remote.proto.AttributeListProto.AttributeAndId parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.yoti.api.client.spi.remote.proto.AttributeListProto.AttributeAndId parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.yoti.api.client.spi.remote.proto.AttributeListProto.AttributeAndId parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.yoti.api.client.spi.remote.proto.AttributeListProto.AttributeAndId parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.yoti.api.client.spi.remote.proto.AttributeListProto.AttributeAndId prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code attrpubapi_v1.AttributeAndId}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:attrpubapi_v1.AttributeAndId)
        com.yoti.api.client.spi.remote.proto.AttributeListProto.AttributeAndIdOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.yoti.api.client.spi.remote.proto.AttributeListProto.internal_static_attrpubapi_v1_AttributeAndId_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.yoti.api.client.spi.remote.proto.AttributeListProto.internal_static_attrpubapi_v1_AttributeAndId_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.yoti.api.client.spi.remote.proto.AttributeListProto.AttributeAndId.class, com.yoti.api.client.spi.remote.proto.AttributeListProto.AttributeAndId.Builder.class);
      }

      // Construct using com.yoti.api.client.spi.remote.proto.AttributeListProto.AttributeAndId.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
          getAttributeFieldBuilder();
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        if (attributeBuilder_ == null) {
          attribute_ = null;
        } else {
          attributeBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000001);
        attributeId_ = com.google.protobuf.ByteString.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.yoti.api.client.spi.remote.proto.AttributeListProto.internal_static_attrpubapi_v1_AttributeAndId_descriptor;
      }

      @java.lang.Override
      public com.yoti.api.client.spi.remote.proto.AttributeListProto.AttributeAndId getDefaultInstanceForType() {
        return com.yoti.api.client.spi.remote.proto.AttributeListProto.AttributeAndId.getDefaultInstance();
      }

      @java.lang.Override
      public com.yoti.api.client.spi.remote.proto.AttributeListProto.AttributeAndId build() {
        com.yoti.api.client.spi.remote.proto.AttributeListProto.AttributeAndId result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.yoti.api.client.spi.remote.proto.AttributeListProto.AttributeAndId buildPartial() {
        com.yoti.api.client.spi.remote.proto.AttributeListProto.AttributeAndId result = new com.yoti.api.client.spi.remote.proto.AttributeListProto.AttributeAndId(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          if (attributeBuilder_ == null) {
            result.attribute_ = attribute_;
          } else {
            result.attribute_ = attributeBuilder_.build();
          }
          to_bitField0_ |= 0x00000001;
        }
        if (((from_bitField0_ & 0x00000002) != 0)) {
          to_bitField0_ |= 0x00000002;
        }
        result.attributeId_ = attributeId_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.yoti.api.client.spi.remote.proto.AttributeListProto.AttributeAndId) {
          return mergeFrom((com.yoti.api.client.spi.remote.proto.AttributeListProto.AttributeAndId)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.yoti.api.client.spi.remote.proto.AttributeListProto.AttributeAndId other) {
        if (other == com.yoti.api.client.spi.remote.proto.AttributeListProto.AttributeAndId.getDefaultInstance()) return this;
        if (other.hasAttribute()) {
          mergeAttribute(other.getAttribute());
        }
        if (other.hasAttributeId()) {
          setAttributeId(other.getAttributeId());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.yoti.api.client.spi.remote.proto.AttributeListProto.AttributeAndId parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.yoti.api.client.spi.remote.proto.AttributeListProto.AttributeAndId) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private com.yoti.api.client.spi.remote.proto.AttributeProto.Attribute attribute_;
      private com.google.protobuf.SingleFieldBuilderV3<
          com.yoti.api.client.spi.remote.proto.AttributeProto.Attribute, com.yoti.api.client.spi.remote.proto.AttributeProto.Attribute.Builder, com.yoti.api.client.spi.remote.proto.AttributeProto.AttributeOrBuilder> attributeBuilder_;
      /**
       * <code>optional .attrpubapi_v1.Attribute attribute = 1;</code>
       * @return Whether the attribute field is set.
       */
      public boolean hasAttribute() {
        return ((bitField0_ & 0x00000001) != 0);
      }
      /**
       * <code>optional .attrpubapi_v1.Attribute attribute = 1;</code>
       * @return The attribute.
       */
      public com.yoti.api.client.spi.remote.proto.AttributeProto.Attribute getAttribute() {
        if (attributeBuilder_ == null) {
          return attribute_ == null ? com.yoti.api.client.spi.remote.proto.AttributeProto.Attribute.getDefaultInstance() : attribute_;
        } else {
          return attributeBuilder_.getMessage();
        }
      }
      /**
       * <code>optional .attrpubapi_v1.Attribute attribute = 1;</code>
       */
      public Builder setAttribute(com.yoti.api.client.spi.remote.proto.AttributeProto.Attribute value) {
        if (attributeBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          attribute_ = value;
          onChanged();
        } else {
          attributeBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000001;
        return this;
      }
      /**
       * <code>optional .attrpubapi_v1.Attribute attribute = 1;</code>
       */
      public Builder setAttribute(
          com.yoti.api.client.spi.remote.proto.AttributeProto.Attribute.Builder builderForValue) {
        if (attributeBuilder_ == null) {
          attribute_ = builderForValue.build();
          onChanged();
        } else {
          attributeBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000001;
        return this;
      }
      /**
       * <code>optional .attrpubapi_v1.Attribute attribute = 1;</code>
       */
      public Builder mergeAttribute(com.yoti.api.client.spi.remote.proto.AttributeProto.Attribute value) {
        if (attributeBuilder_ == null) {
          if (((bitField0_ & 0x00000001) != 0) &&
              attribute_ != null &&
              attribute_ != com.yoti.api.client.spi.remote.proto.AttributeProto.Attribute.getDefaultInstance()) {
            attribute_ =
              com.yoti.api.client.spi.remote.proto.AttributeProto.Attribute.newBuilder(attribute_).mergeFrom(value).buildPartial();
          } else {
            attribute_ = value;
          }
          onChanged();
        } else {
          attributeBuilder_.mergeFrom(value);
        }
        bitField0_ |= 0x00000001;
        return this;
      }
      /**
       * <code>optional .attrpubapi_v1.Attribute attribute = 1;</code>
       */
      public Builder clearAttribute() {
        if (attributeBuilder_ == null) {
          attribute_ = null;
          onChanged();
        } else {
          attributeBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }
      /**
       * <code>optional .attrpubapi_v1.Attribute attribute = 1;</code>
       */
      public com.yoti.api.client.spi.remote.proto.AttributeProto.Attribute.Builder getAttributeBuilder() {
        bitField0_ |= 0x00000001;
        onChanged();
        return getAttributeFieldBuilder().getBuilder();
      }
      /**
       * <code>optional .attrpubapi_v1.Attribute attribute = 1;</code>
       */
      public com.yoti.api.client.spi.remote.proto.AttributeProto.AttributeOrBuilder getAttributeOrBuilder() {
        if (attributeBuilder_ != null) {
          return attributeBuilder_.getMessageOrBuilder();
        } else {
          return attribute_ == null ?
              com.yoti.api.client.spi.remote.proto.AttributeProto.Attribute.getDefaultInstance() : attribute_;
        }
      }
      /**
       * <code>optional .attrpubapi_v1.Attribute attribute = 1;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          com.yoti.api.client.spi.remote.proto.AttributeProto.Attribute, com.yoti.api.client.spi.remote.proto.AttributeProto.Attribute.Builder, com.yoti.api.client.spi.remote.proto.AttributeProto.AttributeOrBuilder> 
          getAttributeFieldBuilder() {
        if (attributeBuilder_ == null) {
          attributeBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              com.yoti.api.client.spi.remote.proto.AttributeProto.Attribute, com.yoti.api.client.spi.remote.proto.AttributeProto.Attribute.Builder, com.yoti.api.client.spi.remote.proto.AttributeProto.AttributeOrBuilder>(
                  getAttribute(),
                  getParentForChildren(),
                  isClean());
          attribute_ = null;
        }
        return attributeBuilder_;
      }

      private com.google.protobuf.ByteString attributeId_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <code>optional bytes attribute_id = 2;</code>
       * @return Whether the attributeId field is set.
       */
      @java.lang.Override
      public boolean hasAttributeId() {
        return ((bitField0_ & 0x00000002) != 0);
      }
      /**
       * <code>optional bytes attribute_id = 2;</code>
       * @return The attributeId.
       */
      @java.lang.Override
      public com.google.protobuf.ByteString getAttributeId() {
        return attributeId_;
      }
      /**
       * <code>optional bytes attribute_id = 2;</code>
       * @param value The attributeId to set.
       * @return This builder for chaining.
       */
      public Builder setAttributeId(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        attributeId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional bytes attribute_id = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearAttributeId() {
        bitField0_ = (bitField0_ & ~0x00000002);
        attributeId_ = getDefaultInstance().getAttributeId();
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:attrpubapi_v1.AttributeAndId)
    }

    // @@protoc_insertion_point(class_scope:attrpubapi_v1.AttributeAndId)
    private static final com.yoti.api.client.spi.remote.proto.AttributeListProto.AttributeAndId DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.yoti.api.client.spi.remote.proto.AttributeListProto.AttributeAndId();
    }

    public static com.yoti.api.client.spi.remote.proto.AttributeListProto.AttributeAndId getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<AttributeAndId>
        PARSER = new com.google.protobuf.AbstractParser<AttributeAndId>() {
      @java.lang.Override
      public AttributeAndId parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new AttributeAndId(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<AttributeAndId> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<AttributeAndId> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.yoti.api.client.spi.remote.proto.AttributeListProto.AttributeAndId getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface AttributeAndIdListOrBuilder extends
      // @@protoc_insertion_point(interface_extends:attrpubapi_v1.AttributeAndIdList)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>repeated .attrpubapi_v1.AttributeAndId attribute_and_id_list = 1;</code>
     */
    java.util.List<com.yoti.api.client.spi.remote.proto.AttributeListProto.AttributeAndId> 
        getAttributeAndIdListList();
    /**
     * <code>repeated .attrpubapi_v1.AttributeAndId attribute_and_id_list = 1;</code>
     */
    com.yoti.api.client.spi.remote.proto.AttributeListProto.AttributeAndId getAttributeAndIdList(int index);
    /**
     * <code>repeated .attrpubapi_v1.AttributeAndId attribute_and_id_list = 1;</code>
     */
    int getAttributeAndIdListCount();
    /**
     * <code>repeated .attrpubapi_v1.AttributeAndId attribute_and_id_list = 1;</code>
     */
    java.util.List<? extends com.yoti.api.client.spi.remote.proto.AttributeListProto.AttributeAndIdOrBuilder> 
        getAttributeAndIdListOrBuilderList();
    /**
     * <code>repeated .attrpubapi_v1.AttributeAndId attribute_and_id_list = 1;</code>
     */
    com.yoti.api.client.spi.remote.proto.AttributeListProto.AttributeAndIdOrBuilder getAttributeAndIdListOrBuilder(
        int index);
  }
  /**
   * Protobuf type {@code attrpubapi_v1.AttributeAndIdList}
   */
  public static final class AttributeAndIdList extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:attrpubapi_v1.AttributeAndIdList)
      AttributeAndIdListOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use AttributeAndIdList.newBuilder() to construct.
    private AttributeAndIdList(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private AttributeAndIdList() {
      attributeAndIdList_ = java.util.Collections.emptyList();
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new AttributeAndIdList();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private AttributeAndIdList(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              if (!((mutable_bitField0_ & 0x00000001) != 0)) {
                attributeAndIdList_ = new java.util.ArrayList<com.yoti.api.client.spi.remote.proto.AttributeListProto.AttributeAndId>();
                mutable_bitField0_ |= 0x00000001;
              }
              attributeAndIdList_.add(
                  input.readMessage(com.yoti.api.client.spi.remote.proto.AttributeListProto.AttributeAndId.parser(), extensionRegistry));
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000001) != 0)) {
          attributeAndIdList_ = java.util.Collections.unmodifiableList(attributeAndIdList_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.yoti.api.client.spi.remote.proto.AttributeListProto.internal_static_attrpubapi_v1_AttributeAndIdList_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.yoti.api.client.spi.remote.proto.AttributeListProto.internal_static_attrpubapi_v1_AttributeAndIdList_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.yoti.api.client.spi.remote.proto.AttributeListProto.AttributeAndIdList.class, com.yoti.api.client.spi.remote.proto.AttributeListProto.AttributeAndIdList.Builder.class);
    }

    public static final int ATTRIBUTE_AND_ID_LIST_FIELD_NUMBER = 1;
    private java.util.List<com.yoti.api.client.spi.remote.proto.AttributeListProto.AttributeAndId> attributeAndIdList_;
    /**
     * <code>repeated .attrpubapi_v1.AttributeAndId attribute_and_id_list = 1;</code>
     */
    @java.lang.Override
    public java.util.List<com.yoti.api.client.spi.remote.proto.AttributeListProto.AttributeAndId> getAttributeAndIdListList() {
      return attributeAndIdList_;
    }
    /**
     * <code>repeated .attrpubapi_v1.AttributeAndId attribute_and_id_list = 1;</code>
     */
    @java.lang.Override
    public java.util.List<? extends com.yoti.api.client.spi.remote.proto.AttributeListProto.AttributeAndIdOrBuilder> 
        getAttributeAndIdListOrBuilderList() {
      return attributeAndIdList_;
    }
    /**
     * <code>repeated .attrpubapi_v1.AttributeAndId attribute_and_id_list = 1;</code>
     */
    @java.lang.Override
    public int getAttributeAndIdListCount() {
      return attributeAndIdList_.size();
    }
    /**
     * <code>repeated .attrpubapi_v1.AttributeAndId attribute_and_id_list = 1;</code>
     */
    @java.lang.Override
    public com.yoti.api.client.spi.remote.proto.AttributeListProto.AttributeAndId getAttributeAndIdList(int index) {
      return attributeAndIdList_.get(index);
    }
    /**
     * <code>repeated .attrpubapi_v1.AttributeAndId attribute_and_id_list = 1;</code>
     */
    @java.lang.Override
    public com.yoti.api.client.spi.remote.proto.AttributeListProto.AttributeAndIdOrBuilder getAttributeAndIdListOrBuilder(
        int index) {
      return attributeAndIdList_.get(index);
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      for (int i = 0; i < attributeAndIdList_.size(); i++) {
        output.writeMessage(1, attributeAndIdList_.get(i));
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      for (int i = 0; i < attributeAndIdList_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, attributeAndIdList_.get(i));
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.yoti.api.client.spi.remote.proto.AttributeListProto.AttributeAndIdList)) {
        return super.equals(obj);
      }
      com.yoti.api.client.spi.remote.proto.AttributeListProto.AttributeAndIdList other = (com.yoti.api.client.spi.remote.proto.AttributeListProto.AttributeAndIdList) obj;

      if (!getAttributeAndIdListList()
          .equals(other.getAttributeAndIdListList())) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (getAttributeAndIdListCount() > 0) {
        hash = (37 * hash) + ATTRIBUTE_AND_ID_LIST_FIELD_NUMBER;
        hash = (53 * hash) + getAttributeAndIdListList().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.yoti.api.client.spi.remote.proto.AttributeListProto.AttributeAndIdList parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.yoti.api.client.spi.remote.proto.AttributeListProto.AttributeAndIdList parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.yoti.api.client.spi.remote.proto.AttributeListProto.AttributeAndIdList parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.yoti.api.client.spi.remote.proto.AttributeListProto.AttributeAndIdList parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.yoti.api.client.spi.remote.proto.AttributeListProto.AttributeAndIdList parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.yoti.api.client.spi.remote.proto.AttributeListProto.AttributeAndIdList parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.yoti.api.client.spi.remote.proto.AttributeListProto.AttributeAndIdList parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.yoti.api.client.spi.remote.proto.AttributeListProto.AttributeAndIdList parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.yoti.api.client.spi.remote.proto.AttributeListProto.AttributeAndIdList parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.yoti.api.client.spi.remote.proto.AttributeListProto.AttributeAndIdList parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.yoti.api.client.spi.remote.proto.AttributeListProto.AttributeAndIdList parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.yoti.api.client.spi.remote.proto.AttributeListProto.AttributeAndIdList parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.yoti.api.client.spi.remote.proto.AttributeListProto.AttributeAndIdList prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code attrpubapi_v1.AttributeAndIdList}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:attrpubapi_v1.AttributeAndIdList)
        com.yoti.api.client.spi.remote.proto.AttributeListProto.AttributeAndIdListOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.yoti.api.client.spi.remote.proto.AttributeListProto.internal_static_attrpubapi_v1_AttributeAndIdList_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.yoti.api.client.spi.remote.proto.AttributeListProto.internal_static_attrpubapi_v1_AttributeAndIdList_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.yoti.api.client.spi.remote.proto.AttributeListProto.AttributeAndIdList.class, com.yoti.api.client.spi.remote.proto.AttributeListProto.AttributeAndIdList.Builder.class);
      }

      // Construct using com.yoti.api.client.spi.remote.proto.AttributeListProto.AttributeAndIdList.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
          getAttributeAndIdListFieldBuilder();
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        if (attributeAndIdListBuilder_ == null) {
          attributeAndIdList_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
        } else {
          attributeAndIdListBuilder_.clear();
        }
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.yoti.api.client.spi.remote.proto.AttributeListProto.internal_static_attrpubapi_v1_AttributeAndIdList_descriptor;
      }

      @java.lang.Override
      public com.yoti.api.client.spi.remote.proto.AttributeListProto.AttributeAndIdList getDefaultInstanceForType() {
        return com.yoti.api.client.spi.remote.proto.AttributeListProto.AttributeAndIdList.getDefaultInstance();
      }

      @java.lang.Override
      public com.yoti.api.client.spi.remote.proto.AttributeListProto.AttributeAndIdList build() {
        com.yoti.api.client.spi.remote.proto.AttributeListProto.AttributeAndIdList result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.yoti.api.client.spi.remote.proto.AttributeListProto.AttributeAndIdList buildPartial() {
        com.yoti.api.client.spi.remote.proto.AttributeListProto.AttributeAndIdList result = new com.yoti.api.client.spi.remote.proto.AttributeListProto.AttributeAndIdList(this);
        int from_bitField0_ = bitField0_;
        if (attributeAndIdListBuilder_ == null) {
          if (((bitField0_ & 0x00000001) != 0)) {
            attributeAndIdList_ = java.util.Collections.unmodifiableList(attributeAndIdList_);
            bitField0_ = (bitField0_ & ~0x00000001);
          }
          result.attributeAndIdList_ = attributeAndIdList_;
        } else {
          result.attributeAndIdList_ = attributeAndIdListBuilder_.build();
        }
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.yoti.api.client.spi.remote.proto.AttributeListProto.AttributeAndIdList) {
          return mergeFrom((com.yoti.api.client.spi.remote.proto.AttributeListProto.AttributeAndIdList)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.yoti.api.client.spi.remote.proto.AttributeListProto.AttributeAndIdList other) {
        if (other == com.yoti.api.client.spi.remote.proto.AttributeListProto.AttributeAndIdList.getDefaultInstance()) return this;
        if (attributeAndIdListBuilder_ == null) {
          if (!other.attributeAndIdList_.isEmpty()) {
            if (attributeAndIdList_.isEmpty()) {
              attributeAndIdList_ = other.attributeAndIdList_;
              bitField0_ = (bitField0_ & ~0x00000001);
            } else {
              ensureAttributeAndIdListIsMutable();
              attributeAndIdList_.addAll(other.attributeAndIdList_);
            }
            onChanged();
          }
        } else {
          if (!other.attributeAndIdList_.isEmpty()) {
            if (attributeAndIdListBuilder_.isEmpty()) {
              attributeAndIdListBuilder_.dispose();
              attributeAndIdListBuilder_ = null;
              attributeAndIdList_ = other.attributeAndIdList_;
              bitField0_ = (bitField0_ & ~0x00000001);
              attributeAndIdListBuilder_ = 
                com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                   getAttributeAndIdListFieldBuilder() : null;
            } else {
              attributeAndIdListBuilder_.addAllMessages(other.attributeAndIdList_);
            }
          }
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.yoti.api.client.spi.remote.proto.AttributeListProto.AttributeAndIdList parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.yoti.api.client.spi.remote.proto.AttributeListProto.AttributeAndIdList) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.util.List<com.yoti.api.client.spi.remote.proto.AttributeListProto.AttributeAndId> attributeAndIdList_ =
        java.util.Collections.emptyList();
      private void ensureAttributeAndIdListIsMutable() {
        if (!((bitField0_ & 0x00000001) != 0)) {
          attributeAndIdList_ = new java.util.ArrayList<com.yoti.api.client.spi.remote.proto.AttributeListProto.AttributeAndId>(attributeAndIdList_);
          bitField0_ |= 0x00000001;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilderV3<
          com.yoti.api.client.spi.remote.proto.AttributeListProto.AttributeAndId, com.yoti.api.client.spi.remote.proto.AttributeListProto.AttributeAndId.Builder, com.yoti.api.client.spi.remote.proto.AttributeListProto.AttributeAndIdOrBuilder> attributeAndIdListBuilder_;

      /**
       * <code>repeated .attrpubapi_v1.AttributeAndId attribute_and_id_list = 1;</code>
       */
      public java.util.List<com.yoti.api.client.spi.remote.proto.AttributeListProto.AttributeAndId> getAttributeAndIdListList() {
        if (attributeAndIdListBuilder_ == null) {
          return java.util.Collections.unmodifiableList(attributeAndIdList_);
        } else {
          return attributeAndIdListBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .attrpubapi_v1.AttributeAndId attribute_and_id_list = 1;</code>
       */
      public int getAttributeAndIdListCount() {
        if (attributeAndIdListBuilder_ == null) {
          return attributeAndIdList_.size();
        } else {
          return attributeAndIdListBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .attrpubapi_v1.AttributeAndId attribute_and_id_list = 1;</code>
       */
      public com.yoti.api.client.spi.remote.proto.AttributeListProto.AttributeAndId getAttributeAndIdList(int index) {
        if (attributeAndIdListBuilder_ == null) {
          return attributeAndIdList_.get(index);
        } else {
          return attributeAndIdListBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .attrpubapi_v1.AttributeAndId attribute_and_id_list = 1;</code>
       */
      public Builder setAttributeAndIdList(
          int index, com.yoti.api.client.spi.remote.proto.AttributeListProto.AttributeAndId value) {
        if (attributeAndIdListBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureAttributeAndIdListIsMutable();
          attributeAndIdList_.set(index, value);
          onChanged();
        } else {
          attributeAndIdListBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .attrpubapi_v1.AttributeAndId attribute_and_id_list = 1;</code>
       */
      public Builder setAttributeAndIdList(
          int index, com.yoti.api.client.spi.remote.proto.AttributeListProto.AttributeAndId.Builder builderForValue) {
        if (attributeAndIdListBuilder_ == null) {
          ensureAttributeAndIdListIsMutable();
          attributeAndIdList_.set(index, builderForValue.build());
          onChanged();
        } else {
          attributeAndIdListBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .attrpubapi_v1.AttributeAndId attribute_and_id_list = 1;</code>
       */
      public Builder addAttributeAndIdList(com.yoti.api.client.spi.remote.proto.AttributeListProto.AttributeAndId value) {
        if (attributeAndIdListBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureAttributeAndIdListIsMutable();
          attributeAndIdList_.add(value);
          onChanged();
        } else {
          attributeAndIdListBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .attrpubapi_v1.AttributeAndId attribute_and_id_list = 1;</code>
       */
      public Builder addAttributeAndIdList(
          int index, com.yoti.api.client.spi.remote.proto.AttributeListProto.AttributeAndId value) {
        if (attributeAndIdListBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureAttributeAndIdListIsMutable();
          attributeAndIdList_.add(index, value);
          onChanged();
        } else {
          attributeAndIdListBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .attrpubapi_v1.AttributeAndId attribute_and_id_list = 1;</code>
       */
      public Builder addAttributeAndIdList(
          com.yoti.api.client.spi.remote.proto.AttributeListProto.AttributeAndId.Builder builderForValue) {
        if (attributeAndIdListBuilder_ == null) {
          ensureAttributeAndIdListIsMutable();
          attributeAndIdList_.add(builderForValue.build());
          onChanged();
        } else {
          attributeAndIdListBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .attrpubapi_v1.AttributeAndId attribute_and_id_list = 1;</code>
       */
      public Builder addAttributeAndIdList(
          int index, com.yoti.api.client.spi.remote.proto.AttributeListProto.AttributeAndId.Builder builderForValue) {
        if (attributeAndIdListBuilder_ == null) {
          ensureAttributeAndIdListIsMutable();
          attributeAndIdList_.add(index, builderForValue.build());
          onChanged();
        } else {
          attributeAndIdListBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .attrpubapi_v1.AttributeAndId attribute_and_id_list = 1;</code>
       */
      public Builder addAllAttributeAndIdList(
          java.lang.Iterable<? extends com.yoti.api.client.spi.remote.proto.AttributeListProto.AttributeAndId> values) {
        if (attributeAndIdListBuilder_ == null) {
          ensureAttributeAndIdListIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, attributeAndIdList_);
          onChanged();
        } else {
          attributeAndIdListBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .attrpubapi_v1.AttributeAndId attribute_and_id_list = 1;</code>
       */
      public Builder clearAttributeAndIdList() {
        if (attributeAndIdListBuilder_ == null) {
          attributeAndIdList_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
          onChanged();
        } else {
          attributeAndIdListBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .attrpubapi_v1.AttributeAndId attribute_and_id_list = 1;</code>
       */
      public Builder removeAttributeAndIdList(int index) {
        if (attributeAndIdListBuilder_ == null) {
          ensureAttributeAndIdListIsMutable();
          attributeAndIdList_.remove(index);
          onChanged();
        } else {
          attributeAndIdListBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .attrpubapi_v1.AttributeAndId attribute_and_id_list = 1;</code>
       */
      public com.yoti.api.client.spi.remote.proto.AttributeListProto.AttributeAndId.Builder getAttributeAndIdListBuilder(
          int index) {
        return getAttributeAndIdListFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .attrpubapi_v1.AttributeAndId attribute_and_id_list = 1;</code>
       */
      public com.yoti.api.client.spi.remote.proto.AttributeListProto.AttributeAndIdOrBuilder getAttributeAndIdListOrBuilder(
          int index) {
        if (attributeAndIdListBuilder_ == null) {
          return attributeAndIdList_.get(index);  } else {
          return attributeAndIdListBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .attrpubapi_v1.AttributeAndId attribute_and_id_list = 1;</code>
       */
      public java.util.List<? extends com.yoti.api.client.spi.remote.proto.AttributeListProto.AttributeAndIdOrBuilder> 
           getAttributeAndIdListOrBuilderList() {
        if (attributeAndIdListBuilder_ != null) {
          return attributeAndIdListBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(attributeAndIdList_);
        }
      }
      /**
       * <code>repeated .attrpubapi_v1.AttributeAndId attribute_and_id_list = 1;</code>
       */
      public com.yoti.api.client.spi.remote.proto.AttributeListProto.AttributeAndId.Builder addAttributeAndIdListBuilder() {
        return getAttributeAndIdListFieldBuilder().addBuilder(
            com.yoti.api.client.spi.remote.proto.AttributeListProto.AttributeAndId.getDefaultInstance());
      }
      /**
       * <code>repeated .attrpubapi_v1.AttributeAndId attribute_and_id_list = 1;</code>
       */
      public com.yoti.api.client.spi.remote.proto.AttributeListProto.AttributeAndId.Builder addAttributeAndIdListBuilder(
          int index) {
        return getAttributeAndIdListFieldBuilder().addBuilder(
            index, com.yoti.api.client.spi.remote.proto.AttributeListProto.AttributeAndId.getDefaultInstance());
      }
      /**
       * <code>repeated .attrpubapi_v1.AttributeAndId attribute_and_id_list = 1;</code>
       */
      public java.util.List<com.yoti.api.client.spi.remote.proto.AttributeListProto.AttributeAndId.Builder> 
           getAttributeAndIdListBuilderList() {
        return getAttributeAndIdListFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilderV3<
          com.yoti.api.client.spi.remote.proto.AttributeListProto.AttributeAndId, com.yoti.api.client.spi.remote.proto.AttributeListProto.AttributeAndId.Builder, com.yoti.api.client.spi.remote.proto.AttributeListProto.AttributeAndIdOrBuilder> 
          getAttributeAndIdListFieldBuilder() {
        if (attributeAndIdListBuilder_ == null) {
          attributeAndIdListBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
              com.yoti.api.client.spi.remote.proto.AttributeListProto.AttributeAndId, com.yoti.api.client.spi.remote.proto.AttributeListProto.AttributeAndId.Builder, com.yoti.api.client.spi.remote.proto.AttributeListProto.AttributeAndIdOrBuilder>(
                  attributeAndIdList_,
                  ((bitField0_ & 0x00000001) != 0),
                  getParentForChildren(),
                  isClean());
          attributeAndIdList_ = null;
        }
        return attributeAndIdListBuilder_;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:attrpubapi_v1.AttributeAndIdList)
    }

    // @@protoc_insertion_point(class_scope:attrpubapi_v1.AttributeAndIdList)
    private static final com.yoti.api.client.spi.remote.proto.AttributeListProto.AttributeAndIdList DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.yoti.api.client.spi.remote.proto.AttributeListProto.AttributeAndIdList();
    }

    public static com.yoti.api.client.spi.remote.proto.AttributeListProto.AttributeAndIdList getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<AttributeAndIdList>
        PARSER = new com.google.protobuf.AbstractParser<AttributeAndIdList>() {
      @java.lang.Override
      public AttributeAndIdList parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new AttributeAndIdList(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<AttributeAndIdList> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<AttributeAndIdList> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.yoti.api.client.spi.remote.proto.AttributeListProto.AttributeAndIdList getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface AttributeListOrBuilder extends
      // @@protoc_insertion_point(interface_extends:attrpubapi_v1.AttributeList)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>repeated .attrpubapi_v1.Attribute attributes = 1;</code>
     */
    java.util.List<com.yoti.api.client.spi.remote.proto.AttributeProto.Attribute> 
        getAttributesList();
    /**
     * <code>repeated .attrpubapi_v1.Attribute attributes = 1;</code>
     */
    com.yoti.api.client.spi.remote.proto.AttributeProto.Attribute getAttributes(int index);
    /**
     * <code>repeated .attrpubapi_v1.Attribute attributes = 1;</code>
     */
    int getAttributesCount();
    /**
     * <code>repeated .attrpubapi_v1.Attribute attributes = 1;</code>
     */
    java.util.List<? extends com.yoti.api.client.spi.remote.proto.AttributeProto.AttributeOrBuilder> 
        getAttributesOrBuilderList();
    /**
     * <code>repeated .attrpubapi_v1.Attribute attributes = 1;</code>
     */
    com.yoti.api.client.spi.remote.proto.AttributeProto.AttributeOrBuilder getAttributesOrBuilder(
        int index);
  }
  /**
   * Protobuf type {@code attrpubapi_v1.AttributeList}
   */
  public static final class AttributeList extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:attrpubapi_v1.AttributeList)
      AttributeListOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use AttributeList.newBuilder() to construct.
    private AttributeList(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private AttributeList() {
      attributes_ = java.util.Collections.emptyList();
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new AttributeList();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private AttributeList(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              if (!((mutable_bitField0_ & 0x00000001) != 0)) {
                attributes_ = new java.util.ArrayList<com.yoti.api.client.spi.remote.proto.AttributeProto.Attribute>();
                mutable_bitField0_ |= 0x00000001;
              }
              attributes_.add(
                  input.readMessage(com.yoti.api.client.spi.remote.proto.AttributeProto.Attribute.parser(), extensionRegistry));
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000001) != 0)) {
          attributes_ = java.util.Collections.unmodifiableList(attributes_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.yoti.api.client.spi.remote.proto.AttributeListProto.internal_static_attrpubapi_v1_AttributeList_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.yoti.api.client.spi.remote.proto.AttributeListProto.internal_static_attrpubapi_v1_AttributeList_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.yoti.api.client.spi.remote.proto.AttributeListProto.AttributeList.class, com.yoti.api.client.spi.remote.proto.AttributeListProto.AttributeList.Builder.class);
    }

    public static final int ATTRIBUTES_FIELD_NUMBER = 1;
    private java.util.List<com.yoti.api.client.spi.remote.proto.AttributeProto.Attribute> attributes_;
    /**
     * <code>repeated .attrpubapi_v1.Attribute attributes = 1;</code>
     */
    @java.lang.Override
    public java.util.List<com.yoti.api.client.spi.remote.proto.AttributeProto.Attribute> getAttributesList() {
      return attributes_;
    }
    /**
     * <code>repeated .attrpubapi_v1.Attribute attributes = 1;</code>
     */
    @java.lang.Override
    public java.util.List<? extends com.yoti.api.client.spi.remote.proto.AttributeProto.AttributeOrBuilder> 
        getAttributesOrBuilderList() {
      return attributes_;
    }
    /**
     * <code>repeated .attrpubapi_v1.Attribute attributes = 1;</code>
     */
    @java.lang.Override
    public int getAttributesCount() {
      return attributes_.size();
    }
    /**
     * <code>repeated .attrpubapi_v1.Attribute attributes = 1;</code>
     */
    @java.lang.Override
    public com.yoti.api.client.spi.remote.proto.AttributeProto.Attribute getAttributes(int index) {
      return attributes_.get(index);
    }
    /**
     * <code>repeated .attrpubapi_v1.Attribute attributes = 1;</code>
     */
    @java.lang.Override
    public com.yoti.api.client.spi.remote.proto.AttributeProto.AttributeOrBuilder getAttributesOrBuilder(
        int index) {
      return attributes_.get(index);
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      for (int i = 0; i < attributes_.size(); i++) {
        output.writeMessage(1, attributes_.get(i));
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      for (int i = 0; i < attributes_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, attributes_.get(i));
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.yoti.api.client.spi.remote.proto.AttributeListProto.AttributeList)) {
        return super.equals(obj);
      }
      com.yoti.api.client.spi.remote.proto.AttributeListProto.AttributeList other = (com.yoti.api.client.spi.remote.proto.AttributeListProto.AttributeList) obj;

      if (!getAttributesList()
          .equals(other.getAttributesList())) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (getAttributesCount() > 0) {
        hash = (37 * hash) + ATTRIBUTES_FIELD_NUMBER;
        hash = (53 * hash) + getAttributesList().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.yoti.api.client.spi.remote.proto.AttributeListProto.AttributeList parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.yoti.api.client.spi.remote.proto.AttributeListProto.AttributeList parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.yoti.api.client.spi.remote.proto.AttributeListProto.AttributeList parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.yoti.api.client.spi.remote.proto.AttributeListProto.AttributeList parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.yoti.api.client.spi.remote.proto.AttributeListProto.AttributeList parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.yoti.api.client.spi.remote.proto.AttributeListProto.AttributeList parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.yoti.api.client.spi.remote.proto.AttributeListProto.AttributeList parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.yoti.api.client.spi.remote.proto.AttributeListProto.AttributeList parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.yoti.api.client.spi.remote.proto.AttributeListProto.AttributeList parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.yoti.api.client.spi.remote.proto.AttributeListProto.AttributeList parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.yoti.api.client.spi.remote.proto.AttributeListProto.AttributeList parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.yoti.api.client.spi.remote.proto.AttributeListProto.AttributeList parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.yoti.api.client.spi.remote.proto.AttributeListProto.AttributeList prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code attrpubapi_v1.AttributeList}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:attrpubapi_v1.AttributeList)
        com.yoti.api.client.spi.remote.proto.AttributeListProto.AttributeListOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.yoti.api.client.spi.remote.proto.AttributeListProto.internal_static_attrpubapi_v1_AttributeList_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.yoti.api.client.spi.remote.proto.AttributeListProto.internal_static_attrpubapi_v1_AttributeList_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.yoti.api.client.spi.remote.proto.AttributeListProto.AttributeList.class, com.yoti.api.client.spi.remote.proto.AttributeListProto.AttributeList.Builder.class);
      }

      // Construct using com.yoti.api.client.spi.remote.proto.AttributeListProto.AttributeList.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
          getAttributesFieldBuilder();
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        if (attributesBuilder_ == null) {
          attributes_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
        } else {
          attributesBuilder_.clear();
        }
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.yoti.api.client.spi.remote.proto.AttributeListProto.internal_static_attrpubapi_v1_AttributeList_descriptor;
      }

      @java.lang.Override
      public com.yoti.api.client.spi.remote.proto.AttributeListProto.AttributeList getDefaultInstanceForType() {
        return com.yoti.api.client.spi.remote.proto.AttributeListProto.AttributeList.getDefaultInstance();
      }

      @java.lang.Override
      public com.yoti.api.client.spi.remote.proto.AttributeListProto.AttributeList build() {
        com.yoti.api.client.spi.remote.proto.AttributeListProto.AttributeList result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.yoti.api.client.spi.remote.proto.AttributeListProto.AttributeList buildPartial() {
        com.yoti.api.client.spi.remote.proto.AttributeListProto.AttributeList result = new com.yoti.api.client.spi.remote.proto.AttributeListProto.AttributeList(this);
        int from_bitField0_ = bitField0_;
        if (attributesBuilder_ == null) {
          if (((bitField0_ & 0x00000001) != 0)) {
            attributes_ = java.util.Collections.unmodifiableList(attributes_);
            bitField0_ = (bitField0_ & ~0x00000001);
          }
          result.attributes_ = attributes_;
        } else {
          result.attributes_ = attributesBuilder_.build();
        }
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.yoti.api.client.spi.remote.proto.AttributeListProto.AttributeList) {
          return mergeFrom((com.yoti.api.client.spi.remote.proto.AttributeListProto.AttributeList)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.yoti.api.client.spi.remote.proto.AttributeListProto.AttributeList other) {
        if (other == com.yoti.api.client.spi.remote.proto.AttributeListProto.AttributeList.getDefaultInstance()) return this;
        if (attributesBuilder_ == null) {
          if (!other.attributes_.isEmpty()) {
            if (attributes_.isEmpty()) {
              attributes_ = other.attributes_;
              bitField0_ = (bitField0_ & ~0x00000001);
            } else {
              ensureAttributesIsMutable();
              attributes_.addAll(other.attributes_);
            }
            onChanged();
          }
        } else {
          if (!other.attributes_.isEmpty()) {
            if (attributesBuilder_.isEmpty()) {
              attributesBuilder_.dispose();
              attributesBuilder_ = null;
              attributes_ = other.attributes_;
              bitField0_ = (bitField0_ & ~0x00000001);
              attributesBuilder_ = 
                com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                   getAttributesFieldBuilder() : null;
            } else {
              attributesBuilder_.addAllMessages(other.attributes_);
            }
          }
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.yoti.api.client.spi.remote.proto.AttributeListProto.AttributeList parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.yoti.api.client.spi.remote.proto.AttributeListProto.AttributeList) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.util.List<com.yoti.api.client.spi.remote.proto.AttributeProto.Attribute> attributes_ =
        java.util.Collections.emptyList();
      private void ensureAttributesIsMutable() {
        if (!((bitField0_ & 0x00000001) != 0)) {
          attributes_ = new java.util.ArrayList<com.yoti.api.client.spi.remote.proto.AttributeProto.Attribute>(attributes_);
          bitField0_ |= 0x00000001;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilderV3<
          com.yoti.api.client.spi.remote.proto.AttributeProto.Attribute, com.yoti.api.client.spi.remote.proto.AttributeProto.Attribute.Builder, com.yoti.api.client.spi.remote.proto.AttributeProto.AttributeOrBuilder> attributesBuilder_;

      /**
       * <code>repeated .attrpubapi_v1.Attribute attributes = 1;</code>
       */
      public java.util.List<com.yoti.api.client.spi.remote.proto.AttributeProto.Attribute> getAttributesList() {
        if (attributesBuilder_ == null) {
          return java.util.Collections.unmodifiableList(attributes_);
        } else {
          return attributesBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .attrpubapi_v1.Attribute attributes = 1;</code>
       */
      public int getAttributesCount() {
        if (attributesBuilder_ == null) {
          return attributes_.size();
        } else {
          return attributesBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .attrpubapi_v1.Attribute attributes = 1;</code>
       */
      public com.yoti.api.client.spi.remote.proto.AttributeProto.Attribute getAttributes(int index) {
        if (attributesBuilder_ == null) {
          return attributes_.get(index);
        } else {
          return attributesBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .attrpubapi_v1.Attribute attributes = 1;</code>
       */
      public Builder setAttributes(
          int index, com.yoti.api.client.spi.remote.proto.AttributeProto.Attribute value) {
        if (attributesBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureAttributesIsMutable();
          attributes_.set(index, value);
          onChanged();
        } else {
          attributesBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .attrpubapi_v1.Attribute attributes = 1;</code>
       */
      public Builder setAttributes(
          int index, com.yoti.api.client.spi.remote.proto.AttributeProto.Attribute.Builder builderForValue) {
        if (attributesBuilder_ == null) {
          ensureAttributesIsMutable();
          attributes_.set(index, builderForValue.build());
          onChanged();
        } else {
          attributesBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .attrpubapi_v1.Attribute attributes = 1;</code>
       */
      public Builder addAttributes(com.yoti.api.client.spi.remote.proto.AttributeProto.Attribute value) {
        if (attributesBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureAttributesIsMutable();
          attributes_.add(value);
          onChanged();
        } else {
          attributesBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .attrpubapi_v1.Attribute attributes = 1;</code>
       */
      public Builder addAttributes(
          int index, com.yoti.api.client.spi.remote.proto.AttributeProto.Attribute value) {
        if (attributesBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureAttributesIsMutable();
          attributes_.add(index, value);
          onChanged();
        } else {
          attributesBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .attrpubapi_v1.Attribute attributes = 1;</code>
       */
      public Builder addAttributes(
          com.yoti.api.client.spi.remote.proto.AttributeProto.Attribute.Builder builderForValue) {
        if (attributesBuilder_ == null) {
          ensureAttributesIsMutable();
          attributes_.add(builderForValue.build());
          onChanged();
        } else {
          attributesBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .attrpubapi_v1.Attribute attributes = 1;</code>
       */
      public Builder addAttributes(
          int index, com.yoti.api.client.spi.remote.proto.AttributeProto.Attribute.Builder builderForValue) {
        if (attributesBuilder_ == null) {
          ensureAttributesIsMutable();
          attributes_.add(index, builderForValue.build());
          onChanged();
        } else {
          attributesBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .attrpubapi_v1.Attribute attributes = 1;</code>
       */
      public Builder addAllAttributes(
          java.lang.Iterable<? extends com.yoti.api.client.spi.remote.proto.AttributeProto.Attribute> values) {
        if (attributesBuilder_ == null) {
          ensureAttributesIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, attributes_);
          onChanged();
        } else {
          attributesBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .attrpubapi_v1.Attribute attributes = 1;</code>
       */
      public Builder clearAttributes() {
        if (attributesBuilder_ == null) {
          attributes_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
          onChanged();
        } else {
          attributesBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .attrpubapi_v1.Attribute attributes = 1;</code>
       */
      public Builder removeAttributes(int index) {
        if (attributesBuilder_ == null) {
          ensureAttributesIsMutable();
          attributes_.remove(index);
          onChanged();
        } else {
          attributesBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .attrpubapi_v1.Attribute attributes = 1;</code>
       */
      public com.yoti.api.client.spi.remote.proto.AttributeProto.Attribute.Builder getAttributesBuilder(
          int index) {
        return getAttributesFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .attrpubapi_v1.Attribute attributes = 1;</code>
       */
      public com.yoti.api.client.spi.remote.proto.AttributeProto.AttributeOrBuilder getAttributesOrBuilder(
          int index) {
        if (attributesBuilder_ == null) {
          return attributes_.get(index);  } else {
          return attributesBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .attrpubapi_v1.Attribute attributes = 1;</code>
       */
      public java.util.List<? extends com.yoti.api.client.spi.remote.proto.AttributeProto.AttributeOrBuilder> 
           getAttributesOrBuilderList() {
        if (attributesBuilder_ != null) {
          return attributesBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(attributes_);
        }
      }
      /**
       * <code>repeated .attrpubapi_v1.Attribute attributes = 1;</code>
       */
      public com.yoti.api.client.spi.remote.proto.AttributeProto.Attribute.Builder addAttributesBuilder() {
        return getAttributesFieldBuilder().addBuilder(
            com.yoti.api.client.spi.remote.proto.AttributeProto.Attribute.getDefaultInstance());
      }
      /**
       * <code>repeated .attrpubapi_v1.Attribute attributes = 1;</code>
       */
      public com.yoti.api.client.spi.remote.proto.AttributeProto.Attribute.Builder addAttributesBuilder(
          int index) {
        return getAttributesFieldBuilder().addBuilder(
            index, com.yoti.api.client.spi.remote.proto.AttributeProto.Attribute.getDefaultInstance());
      }
      /**
       * <code>repeated .attrpubapi_v1.Attribute attributes = 1;</code>
       */
      public java.util.List<com.yoti.api.client.spi.remote.proto.AttributeProto.Attribute.Builder> 
           getAttributesBuilderList() {
        return getAttributesFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilderV3<
          com.yoti.api.client.spi.remote.proto.AttributeProto.Attribute, com.yoti.api.client.spi.remote.proto.AttributeProto.Attribute.Builder, com.yoti.api.client.spi.remote.proto.AttributeProto.AttributeOrBuilder> 
          getAttributesFieldBuilder() {
        if (attributesBuilder_ == null) {
          attributesBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
              com.yoti.api.client.spi.remote.proto.AttributeProto.Attribute, com.yoti.api.client.spi.remote.proto.AttributeProto.Attribute.Builder, com.yoti.api.client.spi.remote.proto.AttributeProto.AttributeOrBuilder>(
                  attributes_,
                  ((bitField0_ & 0x00000001) != 0),
                  getParentForChildren(),
                  isClean());
          attributes_ = null;
        }
        return attributesBuilder_;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:attrpubapi_v1.AttributeList)
    }

    // @@protoc_insertion_point(class_scope:attrpubapi_v1.AttributeList)
    private static final com.yoti.api.client.spi.remote.proto.AttributeListProto.AttributeList DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.yoti.api.client.spi.remote.proto.AttributeListProto.AttributeList();
    }

    public static com.yoti.api.client.spi.remote.proto.AttributeListProto.AttributeList getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<AttributeList>
        PARSER = new com.google.protobuf.AbstractParser<AttributeList>() {
      @java.lang.Override
      public AttributeList parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new AttributeList(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<AttributeList> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<AttributeList> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.yoti.api.client.spi.remote.proto.AttributeListProto.AttributeList getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_attrpubapi_v1_AttributeAndId_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_attrpubapi_v1_AttributeAndId_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_attrpubapi_v1_AttributeAndIdList_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_attrpubapi_v1_AttributeAndIdList_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_attrpubapi_v1_AttributeList_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_attrpubapi_v1_AttributeList_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\nList.proto\022\rattrpubapi_v1\032\017Attribute.p" +
      "roto\"|\n\016AttributeAndId\0220\n\tattribute\030\001 \001(" +
      "\0132\030.attrpubapi_v1.AttributeH\000\210\001\001\022\031\n\014attr" +
      "ibute_id\030\002 \001(\014H\001\210\001\001B\014\n\n_attributeB\017\n\r_at" +
      "tribute_id\"R\n\022AttributeAndIdList\022<\n\025attr" +
      "ibute_and_id_list\030\001 \003(\0132\035.attrpubapi_v1." +
      "AttributeAndId\"=\n\rAttributeList\022,\n\nattri" +
      "butes\030\001 \003(\0132\030.attrpubapi_v1.AttributeB:\n" +
      "$com.yoti.api.client.spi.remote.protoB\022A" +
      "ttributeListProtob\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.yoti.api.client.spi.remote.proto.AttributeProto.getDescriptor(),
        });
    internal_static_attrpubapi_v1_AttributeAndId_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_attrpubapi_v1_AttributeAndId_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_attrpubapi_v1_AttributeAndId_descriptor,
        new java.lang.String[] { "Attribute", "AttributeId", "Attribute", "AttributeId", });
    internal_static_attrpubapi_v1_AttributeAndIdList_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_attrpubapi_v1_AttributeAndIdList_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_attrpubapi_v1_AttributeAndIdList_descriptor,
        new java.lang.String[] { "AttributeAndIdList", });
    internal_static_attrpubapi_v1_AttributeList_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_attrpubapi_v1_AttributeList_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_attrpubapi_v1_AttributeList_descriptor,
        new java.lang.String[] { "Attributes", });
    com.yoti.api.client.spi.remote.proto.AttributeProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
