// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ContentType.proto

package com.yoti.api.client.spi.remote.proto;

public final class ContentTypeProto {
  private ContentTypeProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  /**
   * Protobuf enum {@code attrpubapi_v1.ContentType}
   */
  public enum ContentType
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <code>UNDEFINED = 0;</code>
     */
    UNDEFINED(0),
    /**
     * <code>STRING = 1;</code>
     */
    STRING(1),
    /**
     * <code>JPEG = 2;</code>
     */
    JPEG(2),
    /**
     * <code>DATE = 3;</code>
     */
    DATE(3),
    /**
     * <code>PNG = 4;</code>
     */
    PNG(4),
    /**
     * <code>JSON = 5;</code>
     */
    JSON(5),
    /**
     * <code>MULTI_VALUE = 6;</code>
     */
    MULTI_VALUE(6),
    /**
     * <code>INT = 7;</code>
     */
    INT(7),
    UNRECOGNIZED(-1),
    ;

    /**
     * <code>UNDEFINED = 0;</code>
     */
    public static final int UNDEFINED_VALUE = 0;
    /**
     * <code>STRING = 1;</code>
     */
    public static final int STRING_VALUE = 1;
    /**
     * <code>JPEG = 2;</code>
     */
    public static final int JPEG_VALUE = 2;
    /**
     * <code>DATE = 3;</code>
     */
    public static final int DATE_VALUE = 3;
    /**
     * <code>PNG = 4;</code>
     */
    public static final int PNG_VALUE = 4;
    /**
     * <code>JSON = 5;</code>
     */
    public static final int JSON_VALUE = 5;
    /**
     * <code>MULTI_VALUE = 6;</code>
     */
    public static final int MULTI_VALUE_VALUE = 6;
    /**
     * <code>INT = 7;</code>
     */
    public static final int INT_VALUE = 7;


    public final int getNumber() {
      if (this == UNRECOGNIZED) {
        throw new IllegalArgumentException(
            "Can't get the number of an unknown enum value.");
      }
      return value;
    }

    /**
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @Deprecated
    public static ContentType valueOf(int value) {
      return forNumber(value);
    }

    public static ContentType forNumber(int value) {
      switch (value) {
        case 0: return UNDEFINED;
        case 1: return STRING;
        case 2: return JPEG;
        case 3: return DATE;
        case 4: return PNG;
        case 5: return JSON;
        case 6: return MULTI_VALUE;
        case 7: return INT;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<ContentType>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static final com.google.protobuf.Internal.EnumLiteMap<
        ContentType> internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<ContentType>() {
            public ContentType findValueByNumber(int number) {
              return ContentType.forNumber(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      return getDescriptor().getValues().get(ordinal());
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return ContentTypeProto.getDescriptor().getEnumTypes().get(0);
    }

    private static final ContentType[] VALUES = values();

    public static ContentType valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      if (desc.getIndex() == -1) {
        return UNRECOGNIZED;
      }
      return VALUES[desc.getIndex()];
    }

    private final int value;

    private ContentType(int value) {
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:attrpubapi_v1.ContentType)
  }


  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    String[] descriptorData = {
      "\n\021ContentType.proto\022\rattrpubapi_v1*i\n\013Co" +
      "ntentType\022\r\n\tUNDEFINED\020\000\022\n\n\006STRING\020\001\022\010\n\004" +
      "JPEG\020\002\022\010\n\004DATE\020\003\022\007\n\003PNG\020\004\022\010\n\004JSON\020\005\022\017\n\013M" +
      "ULTI_VALUE\020\006\022\007\n\003INT\020\007Bs\n$com.yoti.api.cl" +
      "ient.spi.remote.protoB\020ContentTypeProtoZ" +
      "\ryotiprotoattr\252\002\034Yoti.Auth.ProtoBuf.Attr" +
      "ibute\312\002\nAttrpubapib\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }

  // @@protoc_insertion_point(outer_class_scope)
}
