// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: EncryptedData.proto

// Protobuf Java Version: 3.25.9
package com.yoti.api.client.spi.remote.proto;

public final class EncryptedDataProto {
  private EncryptedDataProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface EncryptedDataOrBuilder extends
      // @@protoc_insertion_point(interface_extends:compubapi_v1.EncryptedData)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>bytes iv = 1;</code>
     * @return The iv.
     */
    com.google.protobuf.ByteString getIv();

    /**
     * <code>bytes cipher_text = 2;</code>
     * @return The cipherText.
     */
    com.google.protobuf.ByteString getCipherText();
  }
  /**
   * Protobuf type {@code compubapi_v1.EncryptedData}
   */
  public static final class EncryptedData extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:compubapi_v1.EncryptedData)
      EncryptedDataOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use EncryptedData.newBuilder() to construct.
    private EncryptedData(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private EncryptedData() {
      iv_ = com.google.protobuf.ByteString.EMPTY;
      cipherText_ = com.google.protobuf.ByteString.EMPTY;
    }

    @Override
    @SuppressWarnings({"unused"})
    protected Object newInstance(
        UnusedPrivateParameter unused) {
      return new EncryptedData();
    }

    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return EncryptedDataProto.internal_static_compubapi_v1_EncryptedData_descriptor;
    }

    @Override
    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return EncryptedDataProto.internal_static_compubapi_v1_EncryptedData_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              EncryptedData.class, Builder.class);
    }

    public static final int IV_FIELD_NUMBER = 1;
    private com.google.protobuf.ByteString iv_ = com.google.protobuf.ByteString.EMPTY;
    /**
     * <code>bytes iv = 1;</code>
     * @return The iv.
     */
    @Override
    public com.google.protobuf.ByteString getIv() {
      return iv_;
    }

    public static final int CIPHER_TEXT_FIELD_NUMBER = 2;
    private com.google.protobuf.ByteString cipherText_ = com.google.protobuf.ByteString.EMPTY;
    /**
     * <code>bytes cipher_text = 2;</code>
     * @return The cipherText.
     */
    @Override
    public com.google.protobuf.ByteString getCipherText() {
      return cipherText_;
    }

    private byte memoizedIsInitialized = -1;
    @Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!iv_.isEmpty()) {
        output.writeBytes(1, iv_);
      }
      if (!cipherText_.isEmpty()) {
        output.writeBytes(2, cipherText_);
      }
      getUnknownFields().writeTo(output);
    }

    @Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!iv_.isEmpty()) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, iv_);
      }
      if (!cipherText_.isEmpty()) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, cipherText_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @Override
    public boolean equals(final Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof EncryptedData)) {
        return super.equals(obj);
      }
      EncryptedData other = (EncryptedData) obj;

      if (!getIv()
          .equals(other.getIv())) return false;
      if (!getCipherText()
          .equals(other.getCipherText())) return false;
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + IV_FIELD_NUMBER;
      hash = (53 * hash) + getIv().hashCode();
      hash = (37 * hash) + CIPHER_TEXT_FIELD_NUMBER;
      hash = (53 * hash) + getCipherText().hashCode();
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static EncryptedData parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static EncryptedData parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static EncryptedData parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static EncryptedData parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static EncryptedData parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static EncryptedData parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static EncryptedData parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static EncryptedData parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public static EncryptedData parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }

    public static EncryptedData parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static EncryptedData parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static EncryptedData parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(EncryptedData prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @Override
    protected Builder newBuilderForType(
        BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code compubapi_v1.EncryptedData}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:compubapi_v1.EncryptedData)
        EncryptedDataOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return EncryptedDataProto.internal_static_compubapi_v1_EncryptedData_descriptor;
      }

      @Override
      protected FieldAccessorTable
          internalGetFieldAccessorTable() {
        return EncryptedDataProto.internal_static_compubapi_v1_EncryptedData_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                EncryptedData.class, Builder.class);
      }

      // Construct using com.yoti.api.client.spi.remote.proto.EncryptedDataProto.EncryptedData.newBuilder()
      private Builder() {

      }

      private Builder(
          BuilderParent parent) {
        super(parent);

      }
      @Override
      public Builder clear() {
        super.clear();
        bitField0_ = 0;
        iv_ = com.google.protobuf.ByteString.EMPTY;
        cipherText_ = com.google.protobuf.ByteString.EMPTY;
        return this;
      }

      @Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return EncryptedDataProto.internal_static_compubapi_v1_EncryptedData_descriptor;
      }

      @Override
      public EncryptedData getDefaultInstanceForType() {
        return EncryptedData.getDefaultInstance();
      }

      @Override
      public EncryptedData build() {
        EncryptedData result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @Override
      public EncryptedData buildPartial() {
        EncryptedData result = new EncryptedData(this);
        if (bitField0_ != 0) { buildPartial0(result); }
        onBuilt();
        return result;
      }

      private void buildPartial0(EncryptedData result) {
        int from_bitField0_ = bitField0_;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          result.iv_ = iv_;
        }
        if (((from_bitField0_ & 0x00000002) != 0)) {
          result.cipherText_ = cipherText_;
        }
      }

      @Override
      public Builder clone() {
        return super.clone();
      }
      @Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return super.setField(field, value);
      }
      @Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return super.addRepeatedField(field, value);
      }
      @Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof EncryptedData) {
          return mergeFrom((EncryptedData)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(EncryptedData other) {
        if (other == EncryptedData.getDefaultInstance()) return this;
        if (other.getIv() != com.google.protobuf.ByteString.EMPTY) {
          setIv(other.getIv());
        }
        if (other.getCipherText() != com.google.protobuf.ByteString.EMPTY) {
          setCipherText(other.getCipherText());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @Override
      public final boolean isInitialized() {
        return true;
      }

      @Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 10: {
                iv_ = input.readBytes();
                bitField0_ |= 0x00000001;
                break;
              } // case 10
              case 18: {
                cipherText_ = input.readBytes();
                bitField0_ |= 0x00000002;
                break;
              } // case 18
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int bitField0_;

      private com.google.protobuf.ByteString iv_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <code>bytes iv = 1;</code>
       * @return The iv.
       */
      @Override
      public com.google.protobuf.ByteString getIv() {
        return iv_;
      }
      /**
       * <code>bytes iv = 1;</code>
       * @param value The iv to set.
       * @return This builder for chaining.
       */
      public Builder setIv(com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        iv_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <code>bytes iv = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearIv() {
        bitField0_ = (bitField0_ & ~0x00000001);
        iv_ = getDefaultInstance().getIv();
        onChanged();
        return this;
      }

      private com.google.protobuf.ByteString cipherText_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <code>bytes cipher_text = 2;</code>
       * @return The cipherText.
       */
      @Override
      public com.google.protobuf.ByteString getCipherText() {
        return cipherText_;
      }
      /**
       * <code>bytes cipher_text = 2;</code>
       * @param value The cipherText to set.
       * @return This builder for chaining.
       */
      public Builder setCipherText(com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        cipherText_ = value;
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }
      /**
       * <code>bytes cipher_text = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearCipherText() {
        bitField0_ = (bitField0_ & ~0x00000002);
        cipherText_ = getDefaultInstance().getCipherText();
        onChanged();
        return this;
      }
      @Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:compubapi_v1.EncryptedData)
    }

    // @@protoc_insertion_point(class_scope:compubapi_v1.EncryptedData)
    private static final EncryptedData DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new EncryptedData();
    }

    public static EncryptedData getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<EncryptedData>
        PARSER = new com.google.protobuf.AbstractParser<EncryptedData>() {
      @Override
      public EncryptedData parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<EncryptedData> parser() {
      return PARSER;
    }

    @Override
    public com.google.protobuf.Parser<EncryptedData> getParserForType() {
      return PARSER;
    }

    @Override
    public EncryptedData getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_compubapi_v1_EncryptedData_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_compubapi_v1_EncryptedData_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    String[] descriptorData = {
      "\n\023EncryptedData.proto\022\014compubapi_v1\"0\n\rE" +
      "ncryptedData\022\n\n\002iv\030\001 \001(\014\022\023\n\013cipher_text\030" +
      "\002 \001(\014B\342\001\n$com.yoti.api.client.spi.remote" +
      ".protoB\022EncryptedDataProtoZ.github.com/g" +
      "etyoti/yoti-go-sdk/v3/yotiprotocom\252\002\031Yot" +
      "i.Auth.ProtoBuf.Common\312\002\027Yoti\\Protobuf\\C" +
      "ompubapi\342\002#Yoti\\Protobuf\\Compubapi\\GPBMe" +
      "tadata\352\002\031Yoti::Protobuf::Compubapib\006prot" +
      "o3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_compubapi_v1_EncryptedData_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_compubapi_v1_EncryptedData_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_compubapi_v1_EncryptedData_descriptor,
        new String[] { "Iv", "CipherText", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
