// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ExtraData.proto

package com.yoti.api.client.spi.remote.proto;

public final class ExtraDataProto {
  private ExtraDataProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface ExtraDataOrBuilder extends
      // @@protoc_insertion_point(interface_extends:sharepubapi_v1.ExtraData)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>repeated .sharepubapi_v1.DataEntry list = 1;</code>
     */
    java.util.List<DataEntryProto.DataEntry>
        getListList();
    /**
     * <code>repeated .sharepubapi_v1.DataEntry list = 1;</code>
     */
    DataEntryProto.DataEntry getList(int index);
    /**
     * <code>repeated .sharepubapi_v1.DataEntry list = 1;</code>
     */
    int getListCount();
    /**
     * <code>repeated .sharepubapi_v1.DataEntry list = 1;</code>
     */
    java.util.List<? extends DataEntryProto.DataEntryOrBuilder>
        getListOrBuilderList();
    /**
     * <code>repeated .sharepubapi_v1.DataEntry list = 1;</code>
     */
    DataEntryProto.DataEntryOrBuilder getListOrBuilder(
            int index);
  }
  /**
   * Protobuf type {@code sharepubapi_v1.ExtraData}
   */
  public  static final class ExtraData extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:sharepubapi_v1.ExtraData)
      ExtraDataOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use ExtraData.newBuilder() to construct.
    private ExtraData(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private ExtraData() {
      list_ = java.util.Collections.emptyList();
    }

    @Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private ExtraData(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              if (!((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
                list_ = new java.util.ArrayList<DataEntryProto.DataEntry>();
                mutable_bitField0_ |= 0x00000001;
              }
              list_.add(
                  input.readMessage(DataEntryProto.DataEntry.parser(), extensionRegistry));
              break;
            }
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
          list_ = java.util.Collections.unmodifiableList(list_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return ExtraDataProto.internal_static_sharepubapi_v1_ExtraData_descriptor;
    }

    @Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return ExtraDataProto.internal_static_sharepubapi_v1_ExtraData_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              ExtraData.class, Builder.class);
    }

    public static final int LIST_FIELD_NUMBER = 1;
    private java.util.List<DataEntryProto.DataEntry> list_;
    /**
     * <code>repeated .sharepubapi_v1.DataEntry list = 1;</code>
     */
    public java.util.List<DataEntryProto.DataEntry> getListList() {
      return list_;
    }
    /**
     * <code>repeated .sharepubapi_v1.DataEntry list = 1;</code>
     */
    public java.util.List<? extends DataEntryProto.DataEntryOrBuilder>
        getListOrBuilderList() {
      return list_;
    }
    /**
     * <code>repeated .sharepubapi_v1.DataEntry list = 1;</code>
     */
    public int getListCount() {
      return list_.size();
    }
    /**
     * <code>repeated .sharepubapi_v1.DataEntry list = 1;</code>
     */
    public DataEntryProto.DataEntry getList(int index) {
      return list_.get(index);
    }
    /**
     * <code>repeated .sharepubapi_v1.DataEntry list = 1;</code>
     */
    public DataEntryProto.DataEntryOrBuilder getListOrBuilder(
        int index) {
      return list_.get(index);
    }

    private byte memoizedIsInitialized = -1;
    @Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      for (int i = 0; i < list_.size(); i++) {
        output.writeMessage(1, list_.get(i));
      }
      unknownFields.writeTo(output);
    }

    @Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      for (int i = 0; i < list_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, list_.get(i));
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @Override
    public boolean equals(final Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof ExtraData)) {
        return super.equals(obj);
      }
      ExtraData other = (ExtraData) obj;

      boolean result = true;
      result = result && getListList()
          .equals(other.getListList());
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (getListCount() > 0) {
        hash = (37 * hash) + LIST_FIELD_NUMBER;
        hash = (53 * hash) + getListList().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static ExtraData parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static ExtraData parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static ExtraData parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static ExtraData parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static ExtraData parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static ExtraData parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static ExtraData parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static ExtraData parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static ExtraData parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static ExtraData parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static ExtraData parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static ExtraData parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(ExtraData prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code sharepubapi_v1.ExtraData}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:sharepubapi_v1.ExtraData)
        ExtraDataOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return ExtraDataProto.internal_static_sharepubapi_v1_ExtraData_descriptor;
      }

      @Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return ExtraDataProto.internal_static_sharepubapi_v1_ExtraData_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                ExtraData.class, Builder.class);
      }

      // Construct using com.yoti.api.client.spi.remote.proto.ExtraDataProto.ExtraData.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
          getListFieldBuilder();
        }
      }
      @Override
      public Builder clear() {
        super.clear();
        if (listBuilder_ == null) {
          list_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
        } else {
          listBuilder_.clear();
        }
        return this;
      }

      @Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return ExtraDataProto.internal_static_sharepubapi_v1_ExtraData_descriptor;
      }

      @Override
      public ExtraData getDefaultInstanceForType() {
        return ExtraData.getDefaultInstance();
      }

      @Override
      public ExtraData build() {
        ExtraData result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @Override
      public ExtraData buildPartial() {
        ExtraData result = new ExtraData(this);
        int from_bitField0_ = bitField0_;
        if (listBuilder_ == null) {
          if (((bitField0_ & 0x00000001) == 0x00000001)) {
            list_ = java.util.Collections.unmodifiableList(list_);
            bitField0_ = (bitField0_ & ~0x00000001);
          }
          result.list_ = list_;
        } else {
          result.list_ = listBuilder_.build();
        }
        onBuilt();
        return result;
      }

      @Override
      public Builder clone() {
        return (Builder) super.clone();
      }
      @Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      @Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      @Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      @Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      @Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      @Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof ExtraData) {
          return mergeFrom((ExtraData)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(ExtraData other) {
        if (other == ExtraData.getDefaultInstance()) return this;
        if (listBuilder_ == null) {
          if (!other.list_.isEmpty()) {
            if (list_.isEmpty()) {
              list_ = other.list_;
              bitField0_ = (bitField0_ & ~0x00000001);
            } else {
              ensureListIsMutable();
              list_.addAll(other.list_);
            }
            onChanged();
          }
        } else {
          if (!other.list_.isEmpty()) {
            if (listBuilder_.isEmpty()) {
              listBuilder_.dispose();
              listBuilder_ = null;
              list_ = other.list_;
              bitField0_ = (bitField0_ & ~0x00000001);
              listBuilder_ =
                com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                   getListFieldBuilder() : null;
            } else {
              listBuilder_.addAllMessages(other.list_);
            }
          }
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @Override
      public final boolean isInitialized() {
        return true;
      }

      @Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        ExtraData parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (ExtraData) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.util.List<DataEntryProto.DataEntry> list_ =
        java.util.Collections.emptyList();
      private void ensureListIsMutable() {
        if (!((bitField0_ & 0x00000001) == 0x00000001)) {
          list_ = new java.util.ArrayList<DataEntryProto.DataEntry>(list_);
          bitField0_ |= 0x00000001;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilderV3<
          DataEntryProto.DataEntry, DataEntryProto.DataEntry.Builder, DataEntryProto.DataEntryOrBuilder> listBuilder_;

      /**
       * <code>repeated .sharepubapi_v1.DataEntry list = 1;</code>
       */
      public java.util.List<DataEntryProto.DataEntry> getListList() {
        if (listBuilder_ == null) {
          return java.util.Collections.unmodifiableList(list_);
        } else {
          return listBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .sharepubapi_v1.DataEntry list = 1;</code>
       */
      public int getListCount() {
        if (listBuilder_ == null) {
          return list_.size();
        } else {
          return listBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .sharepubapi_v1.DataEntry list = 1;</code>
       */
      public DataEntryProto.DataEntry getList(int index) {
        if (listBuilder_ == null) {
          return list_.get(index);
        } else {
          return listBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .sharepubapi_v1.DataEntry list = 1;</code>
       */
      public Builder setList(
          int index, DataEntryProto.DataEntry value) {
        if (listBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureListIsMutable();
          list_.set(index, value);
          onChanged();
        } else {
          listBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .sharepubapi_v1.DataEntry list = 1;</code>
       */
      public Builder setList(
          int index, DataEntryProto.DataEntry.Builder builderForValue) {
        if (listBuilder_ == null) {
          ensureListIsMutable();
          list_.set(index, builderForValue.build());
          onChanged();
        } else {
          listBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .sharepubapi_v1.DataEntry list = 1;</code>
       */
      public Builder addList(DataEntryProto.DataEntry value) {
        if (listBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureListIsMutable();
          list_.add(value);
          onChanged();
        } else {
          listBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .sharepubapi_v1.DataEntry list = 1;</code>
       */
      public Builder addList(
          int index, DataEntryProto.DataEntry value) {
        if (listBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureListIsMutable();
          list_.add(index, value);
          onChanged();
        } else {
          listBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .sharepubapi_v1.DataEntry list = 1;</code>
       */
      public Builder addList(
          DataEntryProto.DataEntry.Builder builderForValue) {
        if (listBuilder_ == null) {
          ensureListIsMutable();
          list_.add(builderForValue.build());
          onChanged();
        } else {
          listBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .sharepubapi_v1.DataEntry list = 1;</code>
       */
      public Builder addList(
          int index, DataEntryProto.DataEntry.Builder builderForValue) {
        if (listBuilder_ == null) {
          ensureListIsMutable();
          list_.add(index, builderForValue.build());
          onChanged();
        } else {
          listBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .sharepubapi_v1.DataEntry list = 1;</code>
       */
      public Builder addAllList(
          Iterable<? extends DataEntryProto.DataEntry> values) {
        if (listBuilder_ == null) {
          ensureListIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, list_);
          onChanged();
        } else {
          listBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .sharepubapi_v1.DataEntry list = 1;</code>
       */
      public Builder clearList() {
        if (listBuilder_ == null) {
          list_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
          onChanged();
        } else {
          listBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .sharepubapi_v1.DataEntry list = 1;</code>
       */
      public Builder removeList(int index) {
        if (listBuilder_ == null) {
          ensureListIsMutable();
          list_.remove(index);
          onChanged();
        } else {
          listBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .sharepubapi_v1.DataEntry list = 1;</code>
       */
      public DataEntryProto.DataEntry.Builder getListBuilder(
          int index) {
        return getListFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .sharepubapi_v1.DataEntry list = 1;</code>
       */
      public DataEntryProto.DataEntryOrBuilder getListOrBuilder(
          int index) {
        if (listBuilder_ == null) {
          return list_.get(index);  } else {
          return listBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .sharepubapi_v1.DataEntry list = 1;</code>
       */
      public java.util.List<? extends DataEntryProto.DataEntryOrBuilder>
           getListOrBuilderList() {
        if (listBuilder_ != null) {
          return listBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(list_);
        }
      }
      /**
       * <code>repeated .sharepubapi_v1.DataEntry list = 1;</code>
       */
      public DataEntryProto.DataEntry.Builder addListBuilder() {
        return getListFieldBuilder().addBuilder(
            DataEntryProto.DataEntry.getDefaultInstance());
      }
      /**
       * <code>repeated .sharepubapi_v1.DataEntry list = 1;</code>
       */
      public DataEntryProto.DataEntry.Builder addListBuilder(
          int index) {
        return getListFieldBuilder().addBuilder(
            index, DataEntryProto.DataEntry.getDefaultInstance());
      }
      /**
       * <code>repeated .sharepubapi_v1.DataEntry list = 1;</code>
       */
      public java.util.List<DataEntryProto.DataEntry.Builder>
           getListBuilderList() {
        return getListFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilderV3<
          DataEntryProto.DataEntry, DataEntryProto.DataEntry.Builder, DataEntryProto.DataEntryOrBuilder>
          getListFieldBuilder() {
        if (listBuilder_ == null) {
          listBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
              DataEntryProto.DataEntry, DataEntryProto.DataEntry.Builder, DataEntryProto.DataEntryOrBuilder>(
                  list_,
                  ((bitField0_ & 0x00000001) == 0x00000001),
                  getParentForChildren(),
                  isClean());
          list_ = null;
        }
        return listBuilder_;
      }
      @Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      @Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:sharepubapi_v1.ExtraData)
    }

    // @@protoc_insertion_point(class_scope:sharepubapi_v1.ExtraData)
    private static final ExtraData DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new ExtraData();
    }

    public static ExtraData getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<ExtraData>
        PARSER = new com.google.protobuf.AbstractParser<ExtraData>() {
      @Override
      public ExtraData parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new ExtraData(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<ExtraData> parser() {
      return PARSER;
    }

    @Override
    public com.google.protobuf.Parser<ExtraData> getParserForType() {
      return PARSER;
    }

    @Override
    public ExtraData getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_sharepubapi_v1_ExtraData_descriptor;
  private static final
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_sharepubapi_v1_ExtraData_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    String[] descriptorData = {
      "\n\017ExtraData.proto\022\016sharepubapi_v1\032\017DataE" +
      "ntry.proto\"4\n\tExtraData\022\'\n\004list\030\001 \003(\0132\031." +
      "sharepubapi_v1.DataEntryB\257\001\n$com.yoti.ap" +
      "i.client.spi.remote.protoB\016ExtraDataProt" +
      "oZ\016yotiprotoshare\252\002\030Yoti.Auth.ProtoBuf.S" +
      "hare\312\002\020Yoti\\Sharepubapi\342\002\034Yoti\\Sharepuba" +
      "pi\\GPBMetadata\352\002\031Yoti.Protobuf.Sharepuba" +
      "pib\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          DataEntryProto.getDescriptor(),
        }, assigner);
    internal_static_sharepubapi_v1_ExtraData_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_sharepubapi_v1_ExtraData_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_sharepubapi_v1_ExtraData_descriptor,
        new String[] { "List", });
    DataEntryProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
