// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: SignedTimestamp.proto

package com.yoti.api.client.spi.remote.proto;

public final class SignedTimestampProto {
  private SignedTimestampProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface SignedTimestampOrBuilder extends
      // @@protoc_insertion_point(interface_extends:compubapi_v1.SignedTimestamp)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional int32 version = 1;</code>
     * @return Whether the version field is set.
     */
    boolean hasVersion();
    /**
     * <code>optional int32 version = 1;</code>
     * @return The version.
     */
    int getVersion();

    /**
     * <code>optional uint64 timestamp = 2;</code>
     * @return Whether the timestamp field is set.
     */
    boolean hasTimestamp();
    /**
     * <code>optional uint64 timestamp = 2;</code>
     * @return The timestamp.
     */
    long getTimestamp();

    /**
     * <code>optional bytes message_digest = 3;</code>
     * @return Whether the messageDigest field is set.
     */
    boolean hasMessageDigest();
    /**
     * <code>optional bytes message_digest = 3;</code>
     * @return The messageDigest.
     */
    com.google.protobuf.ByteString getMessageDigest();

    /**
     * <code>optional bytes chain_digest = 4;</code>
     * @return Whether the chainDigest field is set.
     */
    boolean hasChainDigest();
    /**
     * <code>optional bytes chain_digest = 4;</code>
     * @return The chainDigest.
     */
    com.google.protobuf.ByteString getChainDigest();

    /**
     * <code>optional bytes chain_digest_skip1 = 5;</code>
     * @return Whether the chainDigestSkip1 field is set.
     */
    boolean hasChainDigestSkip1();
    /**
     * <code>optional bytes chain_digest_skip1 = 5;</code>
     * @return The chainDigestSkip1.
     */
    com.google.protobuf.ByteString getChainDigestSkip1();

    /**
     * <code>optional bytes chain_digest_skip2 = 6;</code>
     * @return Whether the chainDigestSkip2 field is set.
     */
    boolean hasChainDigestSkip2();
    /**
     * <code>optional bytes chain_digest_skip2 = 6;</code>
     * @return The chainDigestSkip2.
     */
    com.google.protobuf.ByteString getChainDigestSkip2();
  }
  /**
   * Protobuf type {@code compubapi_v1.SignedTimestamp}
   */
  public static final class SignedTimestamp extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:compubapi_v1.SignedTimestamp)
      SignedTimestampOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use SignedTimestamp.newBuilder() to construct.
    private SignedTimestamp(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private SignedTimestamp() {
      messageDigest_ = com.google.protobuf.ByteString.EMPTY;
      chainDigest_ = com.google.protobuf.ByteString.EMPTY;
      chainDigestSkip1_ = com.google.protobuf.ByteString.EMPTY;
      chainDigestSkip2_ = com.google.protobuf.ByteString.EMPTY;
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new SignedTimestamp();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private SignedTimestamp(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {
              bitField0_ |= 0x00000001;
              version_ = input.readInt32();
              break;
            }
            case 16: {
              bitField0_ |= 0x00000002;
              timestamp_ = input.readUInt64();
              break;
            }
            case 26: {
              bitField0_ |= 0x00000004;
              messageDigest_ = input.readBytes();
              break;
            }
            case 34: {
              bitField0_ |= 0x00000008;
              chainDigest_ = input.readBytes();
              break;
            }
            case 42: {
              bitField0_ |= 0x00000010;
              chainDigestSkip1_ = input.readBytes();
              break;
            }
            case 50: {
              bitField0_ |= 0x00000020;
              chainDigestSkip2_ = input.readBytes();
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.yoti.api.client.spi.remote.proto.SignedTimestampProto.internal_static_compubapi_v1_SignedTimestamp_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.yoti.api.client.spi.remote.proto.SignedTimestampProto.internal_static_compubapi_v1_SignedTimestamp_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.yoti.api.client.spi.remote.proto.SignedTimestampProto.SignedTimestamp.class, com.yoti.api.client.spi.remote.proto.SignedTimestampProto.SignedTimestamp.Builder.class);
    }

    private int bitField0_;
    public static final int VERSION_FIELD_NUMBER = 1;
    private int version_;
    /**
     * <code>optional int32 version = 1;</code>
     * @return Whether the version field is set.
     */
    @java.lang.Override
    public boolean hasVersion() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <code>optional int32 version = 1;</code>
     * @return The version.
     */
    @java.lang.Override
    public int getVersion() {
      return version_;
    }

    public static final int TIMESTAMP_FIELD_NUMBER = 2;
    private long timestamp_;
    /**
     * <code>optional uint64 timestamp = 2;</code>
     * @return Whether the timestamp field is set.
     */
    @java.lang.Override
    public boolean hasTimestamp() {
      return ((bitField0_ & 0x00000002) != 0);
    }
    /**
     * <code>optional uint64 timestamp = 2;</code>
     * @return The timestamp.
     */
    @java.lang.Override
    public long getTimestamp() {
      return timestamp_;
    }

    public static final int MESSAGE_DIGEST_FIELD_NUMBER = 3;
    private com.google.protobuf.ByteString messageDigest_;
    /**
     * <code>optional bytes message_digest = 3;</code>
     * @return Whether the messageDigest field is set.
     */
    @java.lang.Override
    public boolean hasMessageDigest() {
      return ((bitField0_ & 0x00000004) != 0);
    }
    /**
     * <code>optional bytes message_digest = 3;</code>
     * @return The messageDigest.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString getMessageDigest() {
      return messageDigest_;
    }

    public static final int CHAIN_DIGEST_FIELD_NUMBER = 4;
    private com.google.protobuf.ByteString chainDigest_;
    /**
     * <code>optional bytes chain_digest = 4;</code>
     * @return Whether the chainDigest field is set.
     */
    @java.lang.Override
    public boolean hasChainDigest() {
      return ((bitField0_ & 0x00000008) != 0);
    }
    /**
     * <code>optional bytes chain_digest = 4;</code>
     * @return The chainDigest.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString getChainDigest() {
      return chainDigest_;
    }

    public static final int CHAIN_DIGEST_SKIP1_FIELD_NUMBER = 5;
    private com.google.protobuf.ByteString chainDigestSkip1_;
    /**
     * <code>optional bytes chain_digest_skip1 = 5;</code>
     * @return Whether the chainDigestSkip1 field is set.
     */
    @java.lang.Override
    public boolean hasChainDigestSkip1() {
      return ((bitField0_ & 0x00000010) != 0);
    }
    /**
     * <code>optional bytes chain_digest_skip1 = 5;</code>
     * @return The chainDigestSkip1.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString getChainDigestSkip1() {
      return chainDigestSkip1_;
    }

    public static final int CHAIN_DIGEST_SKIP2_FIELD_NUMBER = 6;
    private com.google.protobuf.ByteString chainDigestSkip2_;
    /**
     * <code>optional bytes chain_digest_skip2 = 6;</code>
     * @return Whether the chainDigestSkip2 field is set.
     */
    @java.lang.Override
    public boolean hasChainDigestSkip2() {
      return ((bitField0_ & 0x00000020) != 0);
    }
    /**
     * <code>optional bytes chain_digest_skip2 = 6;</code>
     * @return The chainDigestSkip2.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString getChainDigestSkip2() {
      return chainDigestSkip2_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) != 0)) {
        output.writeInt32(1, version_);
      }
      if (((bitField0_ & 0x00000002) != 0)) {
        output.writeUInt64(2, timestamp_);
      }
      if (((bitField0_ & 0x00000004) != 0)) {
        output.writeBytes(3, messageDigest_);
      }
      if (((bitField0_ & 0x00000008) != 0)) {
        output.writeBytes(4, chainDigest_);
      }
      if (((bitField0_ & 0x00000010) != 0)) {
        output.writeBytes(5, chainDigestSkip1_);
      }
      if (((bitField0_ & 0x00000020) != 0)) {
        output.writeBytes(6, chainDigestSkip2_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, version_);
      }
      if (((bitField0_ & 0x00000002) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt64Size(2, timestamp_);
      }
      if (((bitField0_ & 0x00000004) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(3, messageDigest_);
      }
      if (((bitField0_ & 0x00000008) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(4, chainDigest_);
      }
      if (((bitField0_ & 0x00000010) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(5, chainDigestSkip1_);
      }
      if (((bitField0_ & 0x00000020) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(6, chainDigestSkip2_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.yoti.api.client.spi.remote.proto.SignedTimestampProto.SignedTimestamp)) {
        return super.equals(obj);
      }
      com.yoti.api.client.spi.remote.proto.SignedTimestampProto.SignedTimestamp other = (com.yoti.api.client.spi.remote.proto.SignedTimestampProto.SignedTimestamp) obj;

      if (hasVersion() != other.hasVersion()) return false;
      if (hasVersion()) {
        if (getVersion()
            != other.getVersion()) return false;
      }
      if (hasTimestamp() != other.hasTimestamp()) return false;
      if (hasTimestamp()) {
        if (getTimestamp()
            != other.getTimestamp()) return false;
      }
      if (hasMessageDigest() != other.hasMessageDigest()) return false;
      if (hasMessageDigest()) {
        if (!getMessageDigest()
            .equals(other.getMessageDigest())) return false;
      }
      if (hasChainDigest() != other.hasChainDigest()) return false;
      if (hasChainDigest()) {
        if (!getChainDigest()
            .equals(other.getChainDigest())) return false;
      }
      if (hasChainDigestSkip1() != other.hasChainDigestSkip1()) return false;
      if (hasChainDigestSkip1()) {
        if (!getChainDigestSkip1()
            .equals(other.getChainDigestSkip1())) return false;
      }
      if (hasChainDigestSkip2() != other.hasChainDigestSkip2()) return false;
      if (hasChainDigestSkip2()) {
        if (!getChainDigestSkip2()
            .equals(other.getChainDigestSkip2())) return false;
      }
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasVersion()) {
        hash = (37 * hash) + VERSION_FIELD_NUMBER;
        hash = (53 * hash) + getVersion();
      }
      if (hasTimestamp()) {
        hash = (37 * hash) + TIMESTAMP_FIELD_NUMBER;
        hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
            getTimestamp());
      }
      if (hasMessageDigest()) {
        hash = (37 * hash) + MESSAGE_DIGEST_FIELD_NUMBER;
        hash = (53 * hash) + getMessageDigest().hashCode();
      }
      if (hasChainDigest()) {
        hash = (37 * hash) + CHAIN_DIGEST_FIELD_NUMBER;
        hash = (53 * hash) + getChainDigest().hashCode();
      }
      if (hasChainDigestSkip1()) {
        hash = (37 * hash) + CHAIN_DIGEST_SKIP1_FIELD_NUMBER;
        hash = (53 * hash) + getChainDigestSkip1().hashCode();
      }
      if (hasChainDigestSkip2()) {
        hash = (37 * hash) + CHAIN_DIGEST_SKIP2_FIELD_NUMBER;
        hash = (53 * hash) + getChainDigestSkip2().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.yoti.api.client.spi.remote.proto.SignedTimestampProto.SignedTimestamp parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.yoti.api.client.spi.remote.proto.SignedTimestampProto.SignedTimestamp parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.yoti.api.client.spi.remote.proto.SignedTimestampProto.SignedTimestamp parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.yoti.api.client.spi.remote.proto.SignedTimestampProto.SignedTimestamp parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.yoti.api.client.spi.remote.proto.SignedTimestampProto.SignedTimestamp parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.yoti.api.client.spi.remote.proto.SignedTimestampProto.SignedTimestamp parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.yoti.api.client.spi.remote.proto.SignedTimestampProto.SignedTimestamp parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.yoti.api.client.spi.remote.proto.SignedTimestampProto.SignedTimestamp parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.yoti.api.client.spi.remote.proto.SignedTimestampProto.SignedTimestamp parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.yoti.api.client.spi.remote.proto.SignedTimestampProto.SignedTimestamp parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.yoti.api.client.spi.remote.proto.SignedTimestampProto.SignedTimestamp parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.yoti.api.client.spi.remote.proto.SignedTimestampProto.SignedTimestamp parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.yoti.api.client.spi.remote.proto.SignedTimestampProto.SignedTimestamp prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code compubapi_v1.SignedTimestamp}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:compubapi_v1.SignedTimestamp)
        com.yoti.api.client.spi.remote.proto.SignedTimestampProto.SignedTimestampOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.yoti.api.client.spi.remote.proto.SignedTimestampProto.internal_static_compubapi_v1_SignedTimestamp_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.yoti.api.client.spi.remote.proto.SignedTimestampProto.internal_static_compubapi_v1_SignedTimestamp_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.yoti.api.client.spi.remote.proto.SignedTimestampProto.SignedTimestamp.class, com.yoti.api.client.spi.remote.proto.SignedTimestampProto.SignedTimestamp.Builder.class);
      }

      // Construct using com.yoti.api.client.spi.remote.proto.SignedTimestampProto.SignedTimestamp.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        version_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        timestamp_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000002);
        messageDigest_ = com.google.protobuf.ByteString.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000004);
        chainDigest_ = com.google.protobuf.ByteString.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000008);
        chainDigestSkip1_ = com.google.protobuf.ByteString.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000010);
        chainDigestSkip2_ = com.google.protobuf.ByteString.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000020);
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.yoti.api.client.spi.remote.proto.SignedTimestampProto.internal_static_compubapi_v1_SignedTimestamp_descriptor;
      }

      @java.lang.Override
      public com.yoti.api.client.spi.remote.proto.SignedTimestampProto.SignedTimestamp getDefaultInstanceForType() {
        return com.yoti.api.client.spi.remote.proto.SignedTimestampProto.SignedTimestamp.getDefaultInstance();
      }

      @java.lang.Override
      public com.yoti.api.client.spi.remote.proto.SignedTimestampProto.SignedTimestamp build() {
        com.yoti.api.client.spi.remote.proto.SignedTimestampProto.SignedTimestamp result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.yoti.api.client.spi.remote.proto.SignedTimestampProto.SignedTimestamp buildPartial() {
        com.yoti.api.client.spi.remote.proto.SignedTimestampProto.SignedTimestamp result = new com.yoti.api.client.spi.remote.proto.SignedTimestampProto.SignedTimestamp(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          result.version_ = version_;
          to_bitField0_ |= 0x00000001;
        }
        if (((from_bitField0_ & 0x00000002) != 0)) {
          result.timestamp_ = timestamp_;
          to_bitField0_ |= 0x00000002;
        }
        if (((from_bitField0_ & 0x00000004) != 0)) {
          to_bitField0_ |= 0x00000004;
        }
        result.messageDigest_ = messageDigest_;
        if (((from_bitField0_ & 0x00000008) != 0)) {
          to_bitField0_ |= 0x00000008;
        }
        result.chainDigest_ = chainDigest_;
        if (((from_bitField0_ & 0x00000010) != 0)) {
          to_bitField0_ |= 0x00000010;
        }
        result.chainDigestSkip1_ = chainDigestSkip1_;
        if (((from_bitField0_ & 0x00000020) != 0)) {
          to_bitField0_ |= 0x00000020;
        }
        result.chainDigestSkip2_ = chainDigestSkip2_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.yoti.api.client.spi.remote.proto.SignedTimestampProto.SignedTimestamp) {
          return mergeFrom((com.yoti.api.client.spi.remote.proto.SignedTimestampProto.SignedTimestamp)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.yoti.api.client.spi.remote.proto.SignedTimestampProto.SignedTimestamp other) {
        if (other == com.yoti.api.client.spi.remote.proto.SignedTimestampProto.SignedTimestamp.getDefaultInstance()) return this;
        if (other.hasVersion()) {
          setVersion(other.getVersion());
        }
        if (other.hasTimestamp()) {
          setTimestamp(other.getTimestamp());
        }
        if (other.hasMessageDigest()) {
          setMessageDigest(other.getMessageDigest());
        }
        if (other.hasChainDigest()) {
          setChainDigest(other.getChainDigest());
        }
        if (other.hasChainDigestSkip1()) {
          setChainDigestSkip1(other.getChainDigestSkip1());
        }
        if (other.hasChainDigestSkip2()) {
          setChainDigestSkip2(other.getChainDigestSkip2());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.yoti.api.client.spi.remote.proto.SignedTimestampProto.SignedTimestamp parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.yoti.api.client.spi.remote.proto.SignedTimestampProto.SignedTimestamp) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private int version_ ;
      /**
       * <code>optional int32 version = 1;</code>
       * @return Whether the version field is set.
       */
      @java.lang.Override
      public boolean hasVersion() {
        return ((bitField0_ & 0x00000001) != 0);
      }
      /**
       * <code>optional int32 version = 1;</code>
       * @return The version.
       */
      @java.lang.Override
      public int getVersion() {
        return version_;
      }
      /**
       * <code>optional int32 version = 1;</code>
       * @param value The version to set.
       * @return This builder for chaining.
       */
      public Builder setVersion(int value) {
        bitField0_ |= 0x00000001;
        version_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 version = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearVersion() {
        bitField0_ = (bitField0_ & ~0x00000001);
        version_ = 0;
        onChanged();
        return this;
      }

      private long timestamp_ ;
      /**
       * <code>optional uint64 timestamp = 2;</code>
       * @return Whether the timestamp field is set.
       */
      @java.lang.Override
      public boolean hasTimestamp() {
        return ((bitField0_ & 0x00000002) != 0);
      }
      /**
       * <code>optional uint64 timestamp = 2;</code>
       * @return The timestamp.
       */
      @java.lang.Override
      public long getTimestamp() {
        return timestamp_;
      }
      /**
       * <code>optional uint64 timestamp = 2;</code>
       * @param value The timestamp to set.
       * @return This builder for chaining.
       */
      public Builder setTimestamp(long value) {
        bitField0_ |= 0x00000002;
        timestamp_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional uint64 timestamp = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearTimestamp() {
        bitField0_ = (bitField0_ & ~0x00000002);
        timestamp_ = 0L;
        onChanged();
        return this;
      }

      private com.google.protobuf.ByteString messageDigest_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <code>optional bytes message_digest = 3;</code>
       * @return Whether the messageDigest field is set.
       */
      @java.lang.Override
      public boolean hasMessageDigest() {
        return ((bitField0_ & 0x00000004) != 0);
      }
      /**
       * <code>optional bytes message_digest = 3;</code>
       * @return The messageDigest.
       */
      @java.lang.Override
      public com.google.protobuf.ByteString getMessageDigest() {
        return messageDigest_;
      }
      /**
       * <code>optional bytes message_digest = 3;</code>
       * @param value The messageDigest to set.
       * @return This builder for chaining.
       */
      public Builder setMessageDigest(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        messageDigest_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional bytes message_digest = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearMessageDigest() {
        bitField0_ = (bitField0_ & ~0x00000004);
        messageDigest_ = getDefaultInstance().getMessageDigest();
        onChanged();
        return this;
      }

      private com.google.protobuf.ByteString chainDigest_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <code>optional bytes chain_digest = 4;</code>
       * @return Whether the chainDigest field is set.
       */
      @java.lang.Override
      public boolean hasChainDigest() {
        return ((bitField0_ & 0x00000008) != 0);
      }
      /**
       * <code>optional bytes chain_digest = 4;</code>
       * @return The chainDigest.
       */
      @java.lang.Override
      public com.google.protobuf.ByteString getChainDigest() {
        return chainDigest_;
      }
      /**
       * <code>optional bytes chain_digest = 4;</code>
       * @param value The chainDigest to set.
       * @return This builder for chaining.
       */
      public Builder setChainDigest(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000008;
        chainDigest_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional bytes chain_digest = 4;</code>
       * @return This builder for chaining.
       */
      public Builder clearChainDigest() {
        bitField0_ = (bitField0_ & ~0x00000008);
        chainDigest_ = getDefaultInstance().getChainDigest();
        onChanged();
        return this;
      }

      private com.google.protobuf.ByteString chainDigestSkip1_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <code>optional bytes chain_digest_skip1 = 5;</code>
       * @return Whether the chainDigestSkip1 field is set.
       */
      @java.lang.Override
      public boolean hasChainDigestSkip1() {
        return ((bitField0_ & 0x00000010) != 0);
      }
      /**
       * <code>optional bytes chain_digest_skip1 = 5;</code>
       * @return The chainDigestSkip1.
       */
      @java.lang.Override
      public com.google.protobuf.ByteString getChainDigestSkip1() {
        return chainDigestSkip1_;
      }
      /**
       * <code>optional bytes chain_digest_skip1 = 5;</code>
       * @param value The chainDigestSkip1 to set.
       * @return This builder for chaining.
       */
      public Builder setChainDigestSkip1(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000010;
        chainDigestSkip1_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional bytes chain_digest_skip1 = 5;</code>
       * @return This builder for chaining.
       */
      public Builder clearChainDigestSkip1() {
        bitField0_ = (bitField0_ & ~0x00000010);
        chainDigestSkip1_ = getDefaultInstance().getChainDigestSkip1();
        onChanged();
        return this;
      }

      private com.google.protobuf.ByteString chainDigestSkip2_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <code>optional bytes chain_digest_skip2 = 6;</code>
       * @return Whether the chainDigestSkip2 field is set.
       */
      @java.lang.Override
      public boolean hasChainDigestSkip2() {
        return ((bitField0_ & 0x00000020) != 0);
      }
      /**
       * <code>optional bytes chain_digest_skip2 = 6;</code>
       * @return The chainDigestSkip2.
       */
      @java.lang.Override
      public com.google.protobuf.ByteString getChainDigestSkip2() {
        return chainDigestSkip2_;
      }
      /**
       * <code>optional bytes chain_digest_skip2 = 6;</code>
       * @param value The chainDigestSkip2 to set.
       * @return This builder for chaining.
       */
      public Builder setChainDigestSkip2(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000020;
        chainDigestSkip2_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional bytes chain_digest_skip2 = 6;</code>
       * @return This builder for chaining.
       */
      public Builder clearChainDigestSkip2() {
        bitField0_ = (bitField0_ & ~0x00000020);
        chainDigestSkip2_ = getDefaultInstance().getChainDigestSkip2();
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:compubapi_v1.SignedTimestamp)
    }

    // @@protoc_insertion_point(class_scope:compubapi_v1.SignedTimestamp)
    private static final com.yoti.api.client.spi.remote.proto.SignedTimestampProto.SignedTimestamp DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.yoti.api.client.spi.remote.proto.SignedTimestampProto.SignedTimestamp();
    }

    public static com.yoti.api.client.spi.remote.proto.SignedTimestampProto.SignedTimestamp getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<SignedTimestamp>
        PARSER = new com.google.protobuf.AbstractParser<SignedTimestamp>() {
      @java.lang.Override
      public SignedTimestamp parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new SignedTimestamp(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<SignedTimestamp> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<SignedTimestamp> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.yoti.api.client.spi.remote.proto.SignedTimestampProto.SignedTimestamp getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_compubapi_v1_SignedTimestamp_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_compubapi_v1_SignedTimestamp_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\025SignedTimestamp.proto\022\014compubapi_v1\"\245\002" +
      "\n\017SignedTimestamp\022\024\n\007version\030\001 \001(\005H\000\210\001\001\022" +
      "\026\n\ttimestamp\030\002 \001(\004H\001\210\001\001\022\033\n\016message_diges" +
      "t\030\003 \001(\014H\002\210\001\001\022\031\n\014chain_digest\030\004 \001(\014H\003\210\001\001\022" +
      "\037\n\022chain_digest_skip1\030\005 \001(\014H\004\210\001\001\022\037\n\022chai" +
      "n_digest_skip2\030\006 \001(\014H\005\210\001\001B\n\n\010_versionB\014\n" +
      "\n_timestampB\021\n\017_message_digestB\017\n\r_chain" +
      "_digestB\025\n\023_chain_digest_skip1B\025\n\023_chain" +
      "_digest_skip2B<\n$com.yoti.api.client.spi" +
      ".remote.protoB\024SignedTimestampProtob\006pro" +
      "to3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_compubapi_v1_SignedTimestamp_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_compubapi_v1_SignedTimestamp_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_compubapi_v1_SignedTimestamp_descriptor,
        new java.lang.String[] { "Version", "Timestamp", "MessageDigest", "ChainDigest", "ChainDigestSkip1", "ChainDigestSkip2", "Version", "Timestamp", "MessageDigest", "ChainDigest", "ChainDigestSkip1", "ChainDigestSkip2", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
