// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: EncryptedData.proto

package com.yoti.api.client.spi.remote.proto;

public final class EncryptedDataProto {
    private EncryptedDataProto() {
    }

    public static void registerAllExtensions(com.google.protobuf.ExtensionRegistry registry) {
    }

    public interface EncryptedDataOrBuilder extends
            // @@protoc_insertion_point(interface_extends:compubapi_v1.EncryptedData)
            com.google.protobuf.MessageOrBuilder {

        /**
         * <code>optional bytes iv = 1;</code>
         *
         * <pre>
         * the iv will be used in conjunction with the secret key
         * received via other channel in order to decrypt the cipher_text
         * </pre>
         */
        boolean hasIv();

        /**
         * <code>optional bytes iv = 1;</code>
         *
         * <pre>
         * the iv will be used in conjunction with the secret key
         * received via other channel in order to decrypt the cipher_text
         * </pre>
         */
        com.google.protobuf.ByteString getIv();

        /**
         * <code>optional bytes cipher_text = 2;</code>
         *
         * <pre>
         * block of bytes to be decrypted
         * </pre>
         */
        boolean hasCipherText();

        /**
         * <code>optional bytes cipher_text = 2;</code>
         *
         * <pre>
         * block of bytes to be decrypted
         * </pre>
         */
        com.google.protobuf.ByteString getCipherText();
    }

    /**
     * Protobuf type {@code compubapi_v1.EncryptedData}
     */
    public static final class EncryptedData extends com.google.protobuf.GeneratedMessage implements
            // @@protoc_insertion_point(message_implements:compubapi_v1.EncryptedData)
            EncryptedDataOrBuilder {
        // Use EncryptedData.newBuilder() to construct.
        private EncryptedData(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
            super(builder);
            this.unknownFields = builder.getUnknownFields();
        }

        private EncryptedData(boolean noInit) {
            this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance();
        }

        private static final EncryptedData defaultInstance;

        public static EncryptedData getDefaultInstance() {
            return defaultInstance;
        }

        @Override
        public EncryptedData getDefaultInstanceForType() {
            return defaultInstance;
        }

        private final com.google.protobuf.UnknownFieldSet unknownFields;

        @java.lang.Override
        public final com.google.protobuf.UnknownFieldSet getUnknownFields() {
            return this.unknownFields;
        }

        private EncryptedData(com.google.protobuf.CodedInputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                        throws com.google.protobuf.InvalidProtocolBufferException {
            initFields();
            int mutable_bitField0_ = 0;
            com.google.protobuf.UnknownFieldSet.Builder unknownFields = com.google.protobuf.UnknownFieldSet
                    .newBuilder();
            try {
                boolean done = false;
                while (!done) {
                    int tag = input.readTag();
                    switch (tag) {
                    case 0:
                        done = true;
                        break;
                    default: {
                        if (!parseUnknownField(input, unknownFields, extensionRegistry, tag)) {
                            done = true;
                        }
                        break;
                    }
                    case 10: {
                        bitField0_ |= 0x00000001;
                        iv_ = input.readBytes();
                        break;
                    }
                    case 18: {
                        bitField0_ |= 0x00000002;
                        cipherText_ = input.readBytes();
                        break;
                    }
                    }
                }
            } catch (com.google.protobuf.InvalidProtocolBufferException e) {
                throw e.setUnfinishedMessage(this);
            } catch (java.io.IOException e) {
                throw new com.google.protobuf.InvalidProtocolBufferException(e.getMessage()).setUnfinishedMessage(this);
            } finally {
                this.unknownFields = unknownFields.build();
                makeExtensionsImmutable();
            }
        }

        public static final com.google.protobuf.Descriptors.Descriptor getDescriptor() {
            return com.yoti.api.client.spi.remote.proto.EncryptedDataProto.internal_static_compubapi_v1_EncryptedData_descriptor;
        }

        @Override
        protected com.google.protobuf.GeneratedMessage.FieldAccessorTable internalGetFieldAccessorTable() {
            return com.yoti.api.client.spi.remote.proto.EncryptedDataProto.internal_static_compubapi_v1_EncryptedData_fieldAccessorTable
                    .ensureFieldAccessorsInitialized(com.yoti.api.client.spi.remote.proto.EncryptedDataProto.EncryptedData.class,
                            com.yoti.api.client.spi.remote.proto.EncryptedDataProto.EncryptedData.Builder.class);
        }

        public static com.google.protobuf.Parser<EncryptedData> PARSER = new com.google.protobuf.AbstractParser<EncryptedData>() {
            @Override
            public EncryptedData parsePartialFrom(com.google.protobuf.CodedInputStream input,
                    com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                            throws com.google.protobuf.InvalidProtocolBufferException {
                return new EncryptedData(input, extensionRegistry);
            }
        };

        @java.lang.Override
        public com.google.protobuf.Parser<EncryptedData> getParserForType() {
            return PARSER;
        }

        private int bitField0_;
        public static final int IV_FIELD_NUMBER = 1;
        private com.google.protobuf.ByteString iv_;

        /**
         * <code>optional bytes iv = 1;</code>
         *
         * <pre>
         * the iv will be used in conjunction with the secret key
         * received via other channel in order to decrypt the cipher_text
         * </pre>
         */
        @Override
        public boolean hasIv() {
            return ((bitField0_ & 0x00000001) == 0x00000001);
        }

        /**
         * <code>optional bytes iv = 1;</code>
         *
         * <pre>
         * the iv will be used in conjunction with the secret key
         * received via other channel in order to decrypt the cipher_text
         * </pre>
         */
        @Override
        public com.google.protobuf.ByteString getIv() {
            return iv_;
        }

        public static final int CIPHER_TEXT_FIELD_NUMBER = 2;
        private com.google.protobuf.ByteString cipherText_;

        /**
         * <code>optional bytes cipher_text = 2;</code>
         *
         * <pre>
         * block of bytes to be decrypted
         * </pre>
         */
        @Override
        public boolean hasCipherText() {
            return ((bitField0_ & 0x00000002) == 0x00000002);
        }

        /**
         * <code>optional bytes cipher_text = 2;</code>
         *
         * <pre>
         * block of bytes to be decrypted
         * </pre>
         */
        @Override
        public com.google.protobuf.ByteString getCipherText() {
            return cipherText_;
        }

        private void initFields() {
            iv_ = com.google.protobuf.ByteString.EMPTY;
            cipherText_ = com.google.protobuf.ByteString.EMPTY;
        }

        private byte memoizedIsInitialized = -1;

        @Override
        public final boolean isInitialized() {
            byte isInitialized = memoizedIsInitialized;
            if (isInitialized == 1) {
                return true;
            }
            if (isInitialized == 0) {
                return false;
            }

            memoizedIsInitialized = 1;
            return true;
        }

        @Override
        public void writeTo(com.google.protobuf.CodedOutputStream output) throws java.io.IOException {
            getSerializedSize();
            if (((bitField0_ & 0x00000001) == 0x00000001)) {
                output.writeBytes(1, iv_);
            }
            if (((bitField0_ & 0x00000002) == 0x00000002)) {
                output.writeBytes(2, cipherText_);
            }
            getUnknownFields().writeTo(output);
        }

        private int memoizedSerializedSize = -1;

        @Override
        public int getSerializedSize() {
            int size = memoizedSerializedSize;
            if (size != -1) {
                return size;
            }

            size = 0;
            if (((bitField0_ & 0x00000001) == 0x00000001)) {
                size += com.google.protobuf.CodedOutputStream.computeBytesSize(1, iv_);
            }
            if (((bitField0_ & 0x00000002) == 0x00000002)) {
                size += com.google.protobuf.CodedOutputStream.computeBytesSize(2, cipherText_);
            }
            size += getUnknownFields().getSerializedSize();
            memoizedSerializedSize = size;
            return size;
        }

        private static final long serialVersionUID = 0L;

        @java.lang.Override
        protected java.lang.Object writeReplace() throws java.io.ObjectStreamException {
            return super.writeReplace();
        }

        public static com.yoti.api.client.spi.remote.proto.EncryptedDataProto.EncryptedData parseFrom(
                com.google.protobuf.ByteString data) throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data);
        }

        public static com.yoti.api.client.spi.remote.proto.EncryptedDataProto.EncryptedData parseFrom(
                com.google.protobuf.ByteString data, com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                        throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data, extensionRegistry);
        }

        public static com.yoti.api.client.spi.remote.proto.EncryptedDataProto.EncryptedData parseFrom(byte[] data)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data);
        }

        public static com.yoti.api.client.spi.remote.proto.EncryptedDataProto.EncryptedData parseFrom(byte[] data,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                        throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data, extensionRegistry);
        }

        public static com.yoti.api.client.spi.remote.proto.EncryptedDataProto.EncryptedData parseFrom(java.io.InputStream input)
                throws java.io.IOException {
            return PARSER.parseFrom(input);
        }

        public static com.yoti.api.client.spi.remote.proto.EncryptedDataProto.EncryptedData parseFrom(java.io.InputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry) throws java.io.IOException {
            return PARSER.parseFrom(input, extensionRegistry);
        }

        public static com.yoti.api.client.spi.remote.proto.EncryptedDataProto.EncryptedData parseDelimitedFrom(
                java.io.InputStream input) throws java.io.IOException {
            return PARSER.parseDelimitedFrom(input);
        }

        public static com.yoti.api.client.spi.remote.proto.EncryptedDataProto.EncryptedData parseDelimitedFrom(
                java.io.InputStream input, com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                        throws java.io.IOException {
            return PARSER.parseDelimitedFrom(input, extensionRegistry);
        }

        public static com.yoti.api.client.spi.remote.proto.EncryptedDataProto.EncryptedData parseFrom(
                com.google.protobuf.CodedInputStream input) throws java.io.IOException {
            return PARSER.parseFrom(input);
        }

        public static com.yoti.api.client.spi.remote.proto.EncryptedDataProto.EncryptedData parseFrom(
                com.google.protobuf.CodedInputStream input, com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                        throws java.io.IOException {
            return PARSER.parseFrom(input, extensionRegistry);
        }

        public static Builder newBuilder() {
            return Builder.create();
        }

        @Override
        public Builder newBuilderForType() {
            return newBuilder();
        }

        public static Builder newBuilder(com.yoti.api.client.spi.remote.proto.EncryptedDataProto.EncryptedData prototype) {
            return newBuilder().mergeFrom(prototype);
        }

        @Override
        public Builder toBuilder() {
            return newBuilder(this);
        }

        @java.lang.Override
        protected Builder newBuilderForType(com.google.protobuf.GeneratedMessage.BuilderParent parent) {
            Builder builder = new Builder(parent);
            return builder;
        }

        /**
         * Protobuf type {@code compubapi_v1.EncryptedData}
         */
        public static final class Builder extends com.google.protobuf.GeneratedMessage.Builder<Builder>implements
                // @@protoc_insertion_point(builder_implements:compubapi_v1.EncryptedData)
                com.yoti.api.client.spi.remote.proto.EncryptedDataProto.EncryptedDataOrBuilder {
            public static final com.google.protobuf.Descriptors.Descriptor getDescriptor() {
                return com.yoti.api.client.spi.remote.proto.EncryptedDataProto.internal_static_compubapi_v1_EncryptedData_descriptor;
            }

            @Override
            protected com.google.protobuf.GeneratedMessage.FieldAccessorTable internalGetFieldAccessorTable() {
                return com.yoti.api.client.spi.remote.proto.EncryptedDataProto.internal_static_compubapi_v1_EncryptedData_fieldAccessorTable
                        .ensureFieldAccessorsInitialized(com.yoti.api.client.spi.remote.proto.EncryptedDataProto.EncryptedData.class,
                                com.yoti.api.client.spi.remote.proto.EncryptedDataProto.EncryptedData.Builder.class);
            }

            // Construct using
            // com.yoti.compubapi_v1.EncryptedDataProto.EncryptedData.newBuilder()
            private Builder() {
                maybeForceBuilderInitialization();
            }

            private Builder(com.google.protobuf.GeneratedMessage.BuilderParent parent) {
                super(parent);
                maybeForceBuilderInitialization();
            }

            private void maybeForceBuilderInitialization() {
                if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
                }
            }

            private static Builder create() {
                return new Builder();
            }

            @Override
            public Builder clear() {
                super.clear();
                iv_ = com.google.protobuf.ByteString.EMPTY;
                bitField0_ = (bitField0_ & ~0x00000001);
                cipherText_ = com.google.protobuf.ByteString.EMPTY;
                bitField0_ = (bitField0_ & ~0x00000002);
                return this;
            }

            @Override
            public Builder clone() {
                return create().mergeFrom(buildPartial());
            }

            @Override
            public com.google.protobuf.Descriptors.Descriptor getDescriptorForType() {
                return com.yoti.api.client.spi.remote.proto.EncryptedDataProto.internal_static_compubapi_v1_EncryptedData_descriptor;
            }

            @Override
            public com.yoti.api.client.spi.remote.proto.EncryptedDataProto.EncryptedData getDefaultInstanceForType() {
                return com.yoti.api.client.spi.remote.proto.EncryptedDataProto.EncryptedData.getDefaultInstance();
            }

            @Override
            public com.yoti.api.client.spi.remote.proto.EncryptedDataProto.EncryptedData build() {
                com.yoti.api.client.spi.remote.proto.EncryptedDataProto.EncryptedData result = buildPartial();
                if (!result.isInitialized()) {
                    throw newUninitializedMessageException(result);
                }
                return result;
            }

            @Override
            public com.yoti.api.client.spi.remote.proto.EncryptedDataProto.EncryptedData buildPartial() {
                com.yoti.api.client.spi.remote.proto.EncryptedDataProto.EncryptedData result = new com.yoti.api.client.spi.remote.proto.EncryptedDataProto.EncryptedData(
                        this);
                int from_bitField0_ = bitField0_;
                int to_bitField0_ = 0;
                if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
                    to_bitField0_ |= 0x00000001;
                }
                result.iv_ = iv_;
                if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
                    to_bitField0_ |= 0x00000002;
                }
                result.cipherText_ = cipherText_;
                result.bitField0_ = to_bitField0_;
                onBuilt();
                return result;
            }

            @Override
            public Builder mergeFrom(com.google.protobuf.Message other) {
                if (other instanceof com.yoti.api.client.spi.remote.proto.EncryptedDataProto.EncryptedData) {
                    return mergeFrom((com.yoti.api.client.spi.remote.proto.EncryptedDataProto.EncryptedData) other);
                } else {
                    super.mergeFrom(other);
                    return this;
                }
            }

            public Builder mergeFrom(com.yoti.api.client.spi.remote.proto.EncryptedDataProto.EncryptedData other) {
                if (other == com.yoti.api.client.spi.remote.proto.EncryptedDataProto.EncryptedData.getDefaultInstance()) {
                    return this;
                }
                if (other.hasIv()) {
                    setIv(other.getIv());
                }
                if (other.hasCipherText()) {
                    setCipherText(other.getCipherText());
                }
                this.mergeUnknownFields(other.getUnknownFields());
                return this;
            }

            @Override
            public final boolean isInitialized() {
                return true;
            }

            @Override
            public Builder mergeFrom(com.google.protobuf.CodedInputStream input,
                    com.google.protobuf.ExtensionRegistryLite extensionRegistry) throws java.io.IOException {
                com.yoti.api.client.spi.remote.proto.EncryptedDataProto.EncryptedData parsedMessage = null;
                try {
                    parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
                } catch (com.google.protobuf.InvalidProtocolBufferException e) {
                    parsedMessage = (com.yoti.api.client.spi.remote.proto.EncryptedDataProto.EncryptedData) e.getUnfinishedMessage();
                    throw e;
                } finally {
                    if (parsedMessage != null) {
                        mergeFrom(parsedMessage);
                    }
                }
                return this;
            }

            private int bitField0_;

            private com.google.protobuf.ByteString iv_ = com.google.protobuf.ByteString.EMPTY;

            /**
             * <code>optional bytes iv = 1;</code>
             *
             * <pre>
             * the iv will be used in conjunction with the secret key
             * received via other channel in order to decrypt the cipher_text
             * </pre>
             */
            @Override
            public boolean hasIv() {
                return ((bitField0_ & 0x00000001) == 0x00000001);
            }

            /**
             * <code>optional bytes iv = 1;</code>
             *
             * <pre>
             * the iv will be used in conjunction with the secret key
             * received via other channel in order to decrypt the cipher_text
             * </pre>
             */
            @Override
            public com.google.protobuf.ByteString getIv() {
                return iv_;
            }

            /**
             * <code>optional bytes iv = 1;</code>
             *
             * <pre>
             * the iv will be used in conjunction with the secret key
             * received via other channel in order to decrypt the cipher_text
             * </pre>
             */
            public Builder setIv(com.google.protobuf.ByteString value) {
                if (value == null) {
                    throw new NullPointerException();
                }
                bitField0_ |= 0x00000001;
                iv_ = value;
                onChanged();
                return this;
            }

            /**
             * <code>optional bytes iv = 1;</code>
             *
             * <pre>
             * the iv will be used in conjunction with the secret key
             * received via other channel in order to decrypt the cipher_text
             * </pre>
             */
            public Builder clearIv() {
                bitField0_ = (bitField0_ & ~0x00000001);
                iv_ = getDefaultInstance().getIv();
                onChanged();
                return this;
            }

            private com.google.protobuf.ByteString cipherText_ = com.google.protobuf.ByteString.EMPTY;

            /**
             * <code>optional bytes cipher_text = 2;</code>
             *
             * <pre>
             * block of bytes to be decrypted
             * </pre>
             */
            @Override
            public boolean hasCipherText() {
                return ((bitField0_ & 0x00000002) == 0x00000002);
            }

            /**
             * <code>optional bytes cipher_text = 2;</code>
             *
             * <pre>
             * block of bytes to be decrypted
             * </pre>
             */
            @Override
            public com.google.protobuf.ByteString getCipherText() {
                return cipherText_;
            }

            /**
             * <code>optional bytes cipher_text = 2;</code>
             *
             * <pre>
             * block of bytes to be decrypted
             * </pre>
             */
            public Builder setCipherText(com.google.protobuf.ByteString value) {
                if (value == null) {
                    throw new NullPointerException();
                }
                bitField0_ |= 0x00000002;
                cipherText_ = value;
                onChanged();
                return this;
            }

            /**
             * <code>optional bytes cipher_text = 2;</code>
             *
             * <pre>
             * block of bytes to be decrypted
             * </pre>
             */
            public Builder clearCipherText() {
                bitField0_ = (bitField0_ & ~0x00000002);
                cipherText_ = getDefaultInstance().getCipherText();
                onChanged();
                return this;
            }

            // @@protoc_insertion_point(builder_scope:compubapi_v1.EncryptedData)
        }

        static {
            defaultInstance = new EncryptedData(true);
            defaultInstance.initFields();
        }

        // @@protoc_insertion_point(class_scope:compubapi_v1.EncryptedData)
    }

    private static final com.google.protobuf.Descriptors.Descriptor internal_static_compubapi_v1_EncryptedData_descriptor;
    private static com.google.protobuf.GeneratedMessage.FieldAccessorTable internal_static_compubapi_v1_EncryptedData_fieldAccessorTable;

    public static com.google.protobuf.Descriptors.FileDescriptor getDescriptor() {
        return descriptor;
    }

    private static com.google.protobuf.Descriptors.FileDescriptor descriptor;

    static {
        java.lang.String[] descriptorData = { "\n\023EncryptedData.proto\022\014compubapi_v1\"0\n\rE"
                + "ncryptedData\022\n\n\002iv\030\001 \001(\014\022\023\n\013cipher_text\030"
                + "\002 \001(\014B+\n\025com.yoti.compubapi_v1B\022Encrypte" + "dDataProto" };
        com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner = new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
            @Override
            public com.google.protobuf.ExtensionRegistry assignDescriptors(
                    com.google.protobuf.Descriptors.FileDescriptor root) {
                descriptor = root;
                return null;
            }
        };
        com.google.protobuf.Descriptors.FileDescriptor.internalBuildGeneratedFileFrom(descriptorData,
                new com.google.protobuf.Descriptors.FileDescriptor[] {}, assigner);
        internal_static_compubapi_v1_EncryptedData_descriptor = getDescriptor().getMessageTypes().get(0);
        internal_static_compubapi_v1_EncryptedData_fieldAccessorTable = new com.google.protobuf.GeneratedMessage.FieldAccessorTable(
                internal_static_compubapi_v1_EncryptedData_descriptor, new java.lang.String[] { "Iv", "CipherText", });
    }

    // @@protoc_insertion_point(outer_class_scope)
}