// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: EncryptedData.proto

package com.yoti.api.client.spi.remote.proto;

public final class EncryptedDataProto {
  private EncryptedDataProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface EncryptedDataOrBuilder extends
      // @@protoc_insertion_point(interface_extends:compubapi_v1.EncryptedData)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>bytes iv = 1;</code>
     */
    com.google.protobuf.ByteString getIv();

    /**
     * <code>bytes cipher_text = 2;</code>
     */
    com.google.protobuf.ByteString getCipherText();
  }
  /**
   * Protobuf type {@code compubapi_v1.EncryptedData}
   */
  public  static final class EncryptedData extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:compubapi_v1.EncryptedData)
      EncryptedDataOrBuilder {
    // Use EncryptedData.newBuilder() to construct.
    private EncryptedData(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private EncryptedData() {
      iv_ = com.google.protobuf.ByteString.EMPTY;
      cipherText_ = com.google.protobuf.ByteString.EMPTY;
    }

    @Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private EncryptedData(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
            case 10: {

              iv_ = input.readBytes();
              break;
            }
            case 18: {

              cipherText_ = input.readBytes();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return EncryptedDataProto.internal_static_compubapi_v1_EncryptedData_descriptor;
    }

    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return EncryptedDataProto.internal_static_compubapi_v1_EncryptedData_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              EncryptedData.class, Builder.class);
    }

    public static final int IV_FIELD_NUMBER = 1;
    private com.google.protobuf.ByteString iv_;
    /**
     * <code>bytes iv = 1;</code>
     */
    public com.google.protobuf.ByteString getIv() {
      return iv_;
    }

    public static final int CIPHER_TEXT_FIELD_NUMBER = 2;
    private com.google.protobuf.ByteString cipherText_;
    /**
     * <code>bytes cipher_text = 2;</code>
     */
    public com.google.protobuf.ByteString getCipherText() {
      return cipherText_;
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!iv_.isEmpty()) {
        output.writeBytes(1, iv_);
      }
      if (!cipherText_.isEmpty()) {
        output.writeBytes(2, cipherText_);
      }
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!iv_.isEmpty()) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, iv_);
      }
      if (!cipherText_.isEmpty()) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, cipherText_);
      }
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @Override
    public boolean equals(final Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof EncryptedData)) {
        return super.equals(obj);
      }
      EncryptedData other = (EncryptedData) obj;

      boolean result = true;
      result = result && getIv()
          .equals(other.getIv());
      result = result && getCipherText()
          .equals(other.getCipherText());
      return result;
    }

    @Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + IV_FIELD_NUMBER;
      hash = (53 * hash) + getIv().hashCode();
      hash = (37 * hash) + CIPHER_TEXT_FIELD_NUMBER;
      hash = (53 * hash) + getCipherText().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static EncryptedData parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static EncryptedData parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static EncryptedData parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static EncryptedData parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static EncryptedData parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static EncryptedData parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static EncryptedData parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static EncryptedData parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static EncryptedData parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static EncryptedData parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(EncryptedData prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @Override
    protected Builder newBuilderForType(
        BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code compubapi_v1.EncryptedData}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:compubapi_v1.EncryptedData)
        EncryptedDataOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return EncryptedDataProto.internal_static_compubapi_v1_EncryptedData_descriptor;
      }

      protected FieldAccessorTable
          internalGetFieldAccessorTable() {
        return EncryptedDataProto.internal_static_compubapi_v1_EncryptedData_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                EncryptedData.class, Builder.class);
      }

      // Construct using com.yoti.api.client.spi.remote.proto.EncryptedDataProto.EncryptedData.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        iv_ = com.google.protobuf.ByteString.EMPTY;

        cipherText_ = com.google.protobuf.ByteString.EMPTY;

        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return EncryptedDataProto.internal_static_compubapi_v1_EncryptedData_descriptor;
      }

      public EncryptedData getDefaultInstanceForType() {
        return EncryptedData.getDefaultInstance();
      }

      public EncryptedData build() {
        EncryptedData result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public EncryptedData buildPartial() {
        EncryptedData result = new EncryptedData(this);
        result.iv_ = iv_;
        result.cipherText_ = cipherText_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof EncryptedData) {
          return mergeFrom((EncryptedData)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(EncryptedData other) {
        if (other == EncryptedData.getDefaultInstance()) return this;
        if (other.getIv() != com.google.protobuf.ByteString.EMPTY) {
          setIv(other.getIv());
        }
        if (other.getCipherText() != com.google.protobuf.ByteString.EMPTY) {
          setCipherText(other.getCipherText());
        }
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        EncryptedData parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (EncryptedData) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private com.google.protobuf.ByteString iv_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <code>bytes iv = 1;</code>
       */
      public com.google.protobuf.ByteString getIv() {
        return iv_;
      }
      /**
       * <code>bytes iv = 1;</code>
       */
      public Builder setIv(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        iv_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>bytes iv = 1;</code>
       */
      public Builder clearIv() {
        
        iv_ = getDefaultInstance().getIv();
        onChanged();
        return this;
      }

      private com.google.protobuf.ByteString cipherText_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <code>bytes cipher_text = 2;</code>
       */
      public com.google.protobuf.ByteString getCipherText() {
        return cipherText_;
      }
      /**
       * <code>bytes cipher_text = 2;</code>
       */
      public Builder setCipherText(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        cipherText_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>bytes cipher_text = 2;</code>
       */
      public Builder clearCipherText() {
        
        cipherText_ = getDefaultInstance().getCipherText();
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:compubapi_v1.EncryptedData)
    }

    // @@protoc_insertion_point(class_scope:compubapi_v1.EncryptedData)
    private static final EncryptedData DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new EncryptedData();
    }

    public static EncryptedData getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<EncryptedData>
        PARSER = new com.google.protobuf.AbstractParser<EncryptedData>() {
      public EncryptedData parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new EncryptedData(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<EncryptedData> parser() {
      return PARSER;
    }

    @Override
    public com.google.protobuf.Parser<EncryptedData> getParserForType() {
      return PARSER;
    }

    public EncryptedData getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_compubapi_v1_EncryptedData_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_compubapi_v1_EncryptedData_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    String[] descriptorData = {
      "\n\023EncryptedData.proto\022\014compubapi_v1\"0\n\rE" +
      "ncryptedData\022\n\n\002iv\030\001 \001(\014\022\023\n\013cipher_text\030" +
      "\002 \001(\014BH\n$com.yoti.api.client.spi.remote." +
      "protoB\022EncryptedDataProtoZ\014yotiprotocomb" +
      "\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_compubapi_v1_EncryptedData_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_compubapi_v1_EncryptedData_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_compubapi_v1_EncryptedData_descriptor,
        new String[] { "Iv", "CipherText", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
