name: Scan
on:
  pull_request:
    branches:
      - 'master'
      - 'DEVELOPMENT*'

jobs:
  sonar:
    name: Scan
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          # Disabling shallow clone is recommended for improving relevancy of reporting
          fetch-depth: 0
      - name: Set up Java 17
        uses: actions/setup-java@v1
        with:
          java-version: 17
          architecture: x64
      - name: Scan SDK
        run: mvn -B clean install sonar:sonar -Ddependency-check.skip=true -Dgpg.skip=true -Dfindbugs.skip=true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
